# make_plain_ppt.py — plain white PPT, text only, maximum detail
from pptx import Presentation
from pptx.util import Inches, Pt
from pptx.dml.color import RGBColor
from pptx.enum.text import PP_ALIGN

prs = Presentation()
prs.slide_width  = Inches(13.33)
prs.slide_height = Inches(7.5)
BLANK = prs.slide_layouts[6]

BLACK  = RGBColor(0x00,0x00,0x00)
GRAY   = RGBColor(0x44,0x44,0x44)
LGRAY  = RGBColor(0x88,0x88,0x88)
WHITE  = RGBColor(0xFF,0xFF,0xFF)
DBLUE  = RGBColor(0x00,0x33,0x88)

def slide():
    sl = prs.slides.add_slide(BLANK)
    bg = sl.background.fill
    bg.solid()
    bg.fore_color.rgb = WHITE
    return sl

def T(sl, text, x, y, w, h, size=13, bold=False,
      color=BLACK, align=PP_ALIGN.LEFT, italic=False):
    tb = sl.shapes.add_textbox(Inches(x), Inches(y), Inches(w), Inches(h))
    tb.word_wrap = True
    tf = tb.text_frame
    tf.word_wrap = True
    p = tf.paragraphs[0]
    p.alignment = align
    r = p.add_run()
    r.text = text
    r.font.size = Pt(size)
    r.font.bold = bold
    r.font.italic = italic
    r.font.color.rgb = color
    return tb

def title(sl, t):
    T(sl, t, 0.3, 0.12, 12.7, 0.65, size=26, bold=True, color=DBLUE)
    # underline rule
    from pptx.util import Inches, Pt, Emu
    ln = sl.shapes.add_shape(1, Inches(0.3), Inches(0.82), Inches(12.7), Pt(2))
    ln.fill.solid(); ln.fill.fore_color.rgb = DBLUE
    ln.line.fill.background()

def body(sl, lines, x=0.35, y=0.98, w=12.6, lh=0.34, base=13):
    """
    lines: list of (indent, text, size, bold, italic)
    indent 0 = normal, 1 = one level, 2 = two levels
    """
    cy = y
    for (ind, txt, sz, bld, itl) in lines:
        ix = x + ind*0.45
        iw = w - ind*0.45
        T(sl, txt, ix, cy, iw, lh+0.05, size=sz,
          bold=bld, italic=itl, color=BLACK if not bld else DBLUE if ind==0 and bld else BLACK)
        cy += lh * (sz/base)
    return cy

# short helper to make a line tuple
def h(text, sz=14, ind=0):   return (ind, text, sz, True,  False)
def p(text, sz=13, ind=1):   return (ind, text, sz, False, False)
def p2(text, sz=12, ind=2):  return (ind, text, sz, False, False)
def it(text, sz=12, ind=1):  return (ind, text, sz, False, True)
def code(text, sz=11, ind=1):return (ind, text, sz, False, True)

# ── SLIDE 1: TITLE ────────────────────────────────────────────
sl = slide()
T(sl,"Smart Campus Asset Manager",0.4,1.2,12.5,1.0,size=36,bold=True,color=DBLUE,align=PP_ALIGN.CENTER)
T(sl,"Design and Analysis of Data Structures and Algorithms — SEng2022",0.4,2.3,12.5,0.5,size=18,color=GRAY,align=PP_ALIGN.CENTER)
T(sl,"Debre Berhan University  |  College of Computing  |  Department of Software Engineering",0.4,2.9,12.5,0.45,size=14,color=GRAY,align=PP_ALIGN.CENTER)
T(sl,"Technology Stack:  C++17  ·  Qt 6 Framework  ·  Oracle XE Database  ·  ODBC Driver",0.4,3.55,12.5,0.4,size=13,color=BLACK,align=PP_ALIGN.CENTER)
T(sl,"DSA Concepts: Stack · Queue · Linked List · BST · Graph · Merge Sort · Greedy · Divide & Conquer",0.4,4.05,12.5,0.4,size=13,color=BLACK,align=PP_ALIGN.CENTER)
T(sl,"Covers All 9 Chapters of the Course Syllabus  |  CLO 1–7  |  All Assessment Criteria Met",0.4,4.55,12.5,0.4,size=13,bold=True,color=BLACK,align=PP_ALIGN.CENTER)
T(sl,"Second Semester 2018 E.C",0.4,6.8,12.5,0.4,size=12,color=LGRAY,align=PP_ALIGN.CENTER)

# ── SLIDE 2: TABLE OF CONTENTS ────────────────────────────────
sl = slide()
title(sl,"Table of Contents")
body(sl,[
h("Part 1 — Project Foundation"),
p("Slide 3:  Project Overview — what the system does, who uses it, roles"),
p("Slide 4:  System Architecture — Qt GUI → DSAEngine → Oracle XE"),
p("Slide 5:  Oracle Database Schema — all 6 tables with columns"),
h("Part 2 — Data Structures & Algorithms (Ch. 1–9)"),
p("Slide 6–8:    Chapter 1  —  Complexity Analysis, Big-O, Omega, Theta"),
p("Slide 9–12:   Chapter 2  —  Bubble Sort, Selection Sort, Linear Search"),
p("Slide 13–15:  Chapter 3  —  Custom Singly-Linked List"),
p("Slide 16–18:  Chapter 4  —  Stack (Undo/Redo) and Queue (Action Log)"),
p("Slide 19–21:  Chapter 5  —  Recursion in BST and DFS"),
p("Slide 22–25:  Chapter 6  —  Binary Search Tree (Serial Index)"),
p("Slide 26–30:  Chapter 7  —  Graph, BFS Shortest Path, DFS Traversal"),
p("Slide 31–34:  Chapter 8  —  Merge Sort (Divide & Conquer)"),
p("Slide 35–38:  Chapter 9  —  Greedy Scheduling, Algorithm Strategies"),
h("Part 3 — Oracle, Testing, Demo"),
p("Slide 39–42:  Oracle — Connection, Reset, Insert Test Data, Verify"),
p("Slide 43–45:  Oracle Stored Procedures — test commands"),
p("Slide 46–47:  Security Check Testing — BST + role access"),
p("Slide 48–49:  Live Demo Guide — click-by-click sequence"),
p("Slide 50:     Conclusion — grade estimate, exam Q&A"),
])

# ── SLIDE 3: PROJECT OVERVIEW ─────────────────────────────────
sl = slide()
title(sl,"Project Overview — Smart Campus Asset Manager")
body(sl,[
h("What the System Does"),
p("Manages all physical assets owned by Debre Berhan University (laptops, lab equipment,"),
p2("furniture, vehicles, security devices) and student-owned devices brought onto campus."),
p("Tracks maintenance requests with priority scheduling, lost & found reports, and"),
p2("campus exit/return checks for student items."),
h("User Roles and Access"),
p("ADMIN       — Full access: add/delete/edit assets, manage users, view all modules"),
p("TECHNICIAN  — View assets, report and resolve maintenance issues, lost & found"),
p("SECURITY    — Campus exit check window only: scan serial numbers, allow/deny exit"),
p("AUDITOR     — Read-only view of assets and maintenance logs"),
p("STUDENT     — Register personal items, report maintenance issues, view lost & found"),
h("Why This Project Demonstrates DSA"),
p("Every major feature is directly powered by a data structure from the course:"),
p2("Undo/Redo  → Stack (Ch.4)    |   Action Log → Linked List (Ch.3)"),
p2("Serial Lookup → BST (Ch.6)   |   Campus Routes → Graph BFS/DFS (Ch.7)"),
p2("Asset Sort → Bubble/Selection/Merge Sort (Ch.2, Ch.8)"),
p2("Maintenance Priority → Greedy Algorithm (Ch.9)"),
h("Files and Modules"),
p("widget.cpp — dashboard, routing, role enforcement"),
p("assetwindow.cpp — asset CRUD + sort + undo/redo"),
p("securitycheckwindow.cpp — BST serial lookup"),
p("maintenancewindow.cpp — greedy auto-prioritize"),
p("campusgraphwindow.cpp — BFS/DFS campus map"),
p("dsaengine.h / dsaengine.cpp — ALL DSA logic isolated here"),
])

# ── SLIDE 4: ARCHITECTURE ─────────────────────────────────────
sl = slide()
title(sl,"System Architecture — Three-Layer Design")
body(sl,[
h("Layer 1: Qt 6 GUI (Presentation Layer)"),
p("All .cpp files except dsaengine: widget, assetwindow, maintenancewindow,"),
p2("lostfoundwindow, studentitemswindow, userswindow, securitycheckwindow, campusgraphwindow"),
p("Responsibilities: display data, capture user input, call DSAEngine, call Oracle via QSqlQuery"),
p("No DSA logic lives here — this layer only calls DSAEngine methods"),
h("Layer 2: DSAEngine (Pure C++ DSA Logic)"),
p("dsaengine.h + dsaengine.cpp — zero Qt dependency, portable C++17"),
p("Contains: Stack<AssetSnapshot>, LLNode linked list, BSTNode tree,"),
p2("adjacency list graph, merge sort, bubble sort, selection sort, greedy sort"),
p("This is the academic heart of the project — every course concept lives here"),
h("Layer 3: Oracle XE (Data Persistence)"),
p("Oracle Express Edition running on localhost:1522/xe"),
p("Schema: campus_admin user, 6 tables, 2 stored procedures"),
p("Qt connects via QODBC driver using Oracle In XE ODBC driver"),
p("All SQL is in the .cpp files via QSqlQuery prepare/bindValue/exec"),
h("Data Flow Example — Add Asset"),
p("User fills form in AssetWindow → QSqlQuery INSERT into ASSETS →"),
p2("DSAEngine.pushUndo(snapshot) → DSAEngine.llEnqueue('ADD:name') →"),
p2("UI refreshes table → stackLabel updates to 'Undo: N | Redo: 0'"),
h("Data Flow Example — Security Check"),
p("Window opens → loadSerialsBST() queries all STUDENT_ITEMS serials → BST built →"),
p2("User types serial → DSAEngine.bstSearch() runs O(log n) →"),
p2("Result shown in blue bar → QSqlQuery fetches full record → table populated"),
])

# ── SLIDE 5: ORACLE SCHEMA ────────────────────────────────────
sl = slide()
title(sl,"Oracle Database Schema — All 6 Tables")
body(sl,[
h("ASSETS"),
p("ASSET_ID        NUMBER(10) PRIMARY KEY  — auto from SEQ_ASSETS sequence"),
p("ASSET_NAME      VARCHAR2(100) NOT NULL"),
p("CATEGORY        VARCHAR2(50)  — IT_EQUIPMENT|LAB_EQUIPMENT|FURNITURE|VEHICLES|etc."),
p("SERIAL_NUMBER   VARCHAR2(50)  UNIQUE"),
p("PURCHASE_VALUE  NUMBER(12,2)"),
p("CONDITION       VARCHAR2(30)  — GOOD|BROKEN|UNDER_MAINTENANCE|DECOMMISSIONED"),
p("LOCATION_ID     NUMBER(10)    FK → LOCATIONS"),
p("CREATED_BY      NUMBER(10)    FK → USERS"),
p("UPDATED_AT      DATE"),
h("STUDENT_ITEMS"),
p("ITEM_ID        NUMBER(10) PRIMARY KEY"),
p("STUDENT_ID     NUMBER(10) FK → USERS"),
p("ITEM_NAME      VARCHAR2(100), CATEGORY VARCHAR2(50), BRAND VARCHAR2(50)"),
p("SERIAL_NUMBER  VARCHAR2(50) — indexed by BST in SecurityCheckWindow"),
p("STATUS         VARCHAR2(30) — REGISTERED | OUT_OF_CAMPUS"),
h("MAINTENANCE_LOG"),
p("MAINTENANCE_ID  NUMBER(10) PRIMARY KEY — auto from SEQ_MAINTENANCE"),
p("ASSET_ID        FK → ASSETS,   REPORTED_BY FK → USERS"),
p("DESCRIPTION     VARCHAR2(500), ISSUE_TYPE VARCHAR2(30)"),
p("PRIORITY        VARCHAR2(10)  — URGENT|HIGH|NORMAL|LOW  (used by Greedy)"),
p("STATUS          VARCHAR2(20)  — PENDING|IN_PROGRESS|RESOLVED|CANCELLED"),
p("REPORTED_AT     DATE DEFAULT SYSDATE,  RESOLVED_AT DATE"),
h("USERS / LOST_FOUND / LOCATIONS"),
p("USERS: USER_ID, FULL_NAME, STUDENT_ID, EMAIL, ROLE, PASSWORD_HASH"),
p("LOST_FOUND: LF_ID, REPORTED_BY, ITEM_TYPE, DESCRIPTION, LOCATION, STATUS"),
p("LOCATIONS: LOCATION_ID, BUILDING_NAME, ROOM_NUMBER, FLOOR"),
])

# ── SLIDE 6: CH1 DIVIDER ──────────────────────────────────────
sl = slide()
title(sl,"Chapter 1 — Introduction to Data Structures and Algorithms")
body(sl,[
h("Chapter Overview"),
p("This chapter introduces the foundational concepts that underpin all subsequent chapters."),
p("Topics: Abstract Data Types (ADT), algorithm properties, performance analysis,"),
p2("asymptotic notation (Big-O, Omega, Theta), and complexity classes."),
h("What is an Abstract Data Type (ADT)?"),
p("An ADT defines WHAT operations are available but not HOW they are implemented."),
p("Example: Stack ADT defines push(), pop(), peek(), isEmpty() — the implementation"),
p2("(array-based or linked-list-based) is hidden from the user."),
p("In our project, DSAEngine is the implementation of multiple ADTs combined."),
h("What is an Algorithm?"),
p("An algorithm is a finite set of well-defined steps that solves a problem."),
p("Properties: Input, Output, Definiteness, Finiteness, Effectiveness"),
p("Every function in dsaengine.cpp is an algorithm satisfying all 5 properties."),
h("Why Complexity Analysis Matters"),
p("Two algorithms can produce the same output but differ enormously in time/space used."),
p("Example: bubbleSortById() vs mergeSortByValue() both sort the same asset list"),
p2("but bubble is O(n²) and merge is O(n log n). For 1000 assets:"),
p2("Bubble: up to 1,000,000 comparisons   Merge: ~10,000 comparisons"),
h("Covered in Our Project"),
p("Every function in dsaengine.cpp has a comment block above it stating:"),
p2("Time complexity: Best / Average / Worst case"),
p2("Space complexity: auxiliary memory used"),
p2("The formula derivation (e.g. T(n) = 2T(n/2) + O(n) for Merge Sort)"),
])

# ── SLIDE 7: ASYMPTOTIC NOTATION ──────────────────────────────
sl = slide()
title(sl,"Asymptotic Notation — Big-O, Omega, Theta")
body(sl,[
h("Big-O Notation  O(f(n))  —  Upper Bound (Worst Case)"),
p("Definition: T(n) = O(f(n)) means T(n) ≤ c·f(n) for all n ≥ n₀"),
p("Interpretation: the algorithm will NEVER be slower than O(f(n))"),
p("Used for: guaranteeing maximum resource usage"),
p2("Example: bubbleSortById() is O(n²) — at most n²/2 comparisons"),
p2("Example: bstSearch() is O(n) worst case — degenerate BST (sorted insertion)"),
h("Omega Notation  Ω(f(n))  —  Lower Bound (Best Case)"),
p("Definition: T(n) = Ω(f(n)) means T(n) ≥ c·f(n) for all n ≥ n₀"),
p("Interpretation: the algorithm always takes AT LEAST Ω(f(n)) time"),
p2("Example: any sort algorithm is Ω(n log n) — must read every element at least once"),
p2("Example: bstSearch() best case is Ω(1) — root node is the target"),
h("Theta Notation  Θ(f(n))  —  Tight Bound (Exact Growth)"),
p("Definition: T(n) = Θ(f(n)) when both O(f(n)) and Ω(f(n)) hold"),
p("Interpretation: the exact growth rate, not just an upper or lower bound"),
p2("Example: Merge Sort is Θ(n log n) — same in best, average, and worst case"),
p2("Example: Bubble Sort is Θ(n²) — always n²/2 comparisons regardless of input"),
h("Practical Complexity Classes"),
p("O(1)        Stack push/pop, linked list head insert/remove"),
p("O(log n)    BST search (balanced), Binary Search"),
p("O(n)        Linear search, array traversal"),
p("O(n log n)  Merge Sort, BST build from n elements"),
p("O(n²)       Bubble Sort, Selection Sort"),
p("O(V+E)      BFS and DFS graph traversal"),
h("How to Calculate: Bubble Sort Example"),
p("Inner loop runs (n-1) + (n-2) + ... + 1 = n(n-1)/2 times"),
p("n(n-1)/2 = (n²-n)/2.  Drop lower terms and constants → O(n²)"),
])

# ── SLIDE 8: COMPLEXITY TABLE ─────────────────────────────────
sl = slide()
title(sl,"Complexity Table — Every DSAEngine Function")
body(sl,[
h("Sorting Algorithms"),
p("bubbleSortById()       Time: O(n²) / O(n²) / O(n²)   Space: O(1)   File: dsaengine.cpp line ~100"),
p("bubbleSortByValue()    Time: O(n²) / O(n²) / O(n²)   Space: O(1)   File: dsaengine.cpp line ~115"),
p("selectionSortByName()  Time: O(n²) / O(n²) / O(n²)   Space: O(1)   File: dsaengine.cpp line ~130"),
p("selectionSortByLoc()   Time: O(n²) / O(n²) / O(n²)   Space: O(1)   File: dsaengine.cpp line ~148"),
p("mergeSortByValue()     Time: O(nlogn)/O(nlogn)/O(nlogn) Space: O(n) File: dsaengine.cpp"),
p("mergeSortByName()      Time: O(nlogn)/O(nlogn)/O(nlogn) Space: O(n) File: dsaengine.cpp"),
h("Stack Operations"),
p("pushUndo()   Time: O(1) amortized, O(n) at MAX_STACK_SIZE cap   Space: O(n) total stack"),
p("popUndo()    Time: O(1)   Space: O(1)"),
p("pushRedo()   Time: O(1)   Space: O(n) total stack"),
p("popRedo()    Time: O(1)   Space: O(1)"),
h("Linked List (Action Log)"),
p("llEnqueue()  Time: O(1) — tail pointer allows direct append   Space: O(1) per node"),
p("llDequeue()  Time: O(1) — head pointer allows direct removal  Space: O(1)"),
p("llContents() Time: O(n) — must traverse all nodes             Space: O(n) for output"),
h("Binary Search Tree"),
p("bstInsert()  Time: O(log n) average, O(n) worst   Space: O(log n) stack depth (recursion)"),
p("bstSearch()  Time: O(log n) average, O(n) worst   Space: O(log n) stack depth"),
p("bstClear()   Time: O(n) — visits every node       Space: O(n) stack depth"),
p("bstHeight()  Time: O(n)                           Space: O(n) stack depth"),
h("Graph Traversal"),
p("graphBFS()   Time: O(V+E)   Space: O(V) — queue + visited set + parent map"),
p("graphDFS()   Time: O(V+E)   Space: O(V) — recursion stack + visited set"),
p("graphInit()  Time: O(E)     Space: O(V+E) for adjacency list"),
h("Note on Worst Cases"),
p("Stack worst case O(n): only when size hits MAX_STACK_SIZE=20, oldest entry drained"),
p("BST worst case O(n): only when all serials inserted in alphabetical order (degenerate tree)"),
p("In practice with random serial numbers, BST stays balanced → O(log n) guaranteed"),
])

# ── SLIDE 9: CH2 DIVIDER ──────────────────────────────────────
sl = slide()
title(sl,"Chapter 2 — Simple Sorting and Searching Algorithms")
body(sl,[
h("Chapter Overview"),
p("Covers the foundational sorting algorithms that every programmer must know."),
p("Sorting algorithms covered: Insertion Sort (theory), Bubble Sort (implemented),"),
p2("Selection Sort (implemented). Searching: Linear Search (implemented via SQL),"),
p2("Binary Search (concept, implemented via BST structure in Ch.6)."),
h("Why Sorting is Critical"),
p("Sorting enables binary search (O(log n) vs O(n) for unsorted data)."),
p("Sorted display helps users find assets faster in the Asset Manager."),
p("In our app, users can sort the asset table by ID, value, name, or location."),
h("Algorithms Implemented in Our Project"),
p("Bubble Sort — bubbleSortById() and bubbleSortByValue() in dsaengine.cpp"),
p("Selection Sort — selectionSortByName() and selectionSortByLocation() in dsaengine.cpp"),
p("Linear Search — done via Oracle SQL LIKE operator in securitycheckwindow.cpp"),
p("BST Search — binary search tree structure provides O(log n) serial lookup"),
h("Where They Are Called"),
p("assetwindow.cpp → sortAssets() method:"),
p2("'ID (Bubble Sort)'        → m_dsa.bubbleSortById(records)"),
p2("'Value (Bubble Sort)'     → m_dsa.bubbleSortByValue(records)"),
p2("'Name (Selection Sort)'   → m_dsa.selectionSortByName(records)"),
p2("'Location (Selection Sort)' → m_dsa.selectionSortByLocation(records)"),
p2("'Value (Merge Sort - D&C)' → m_dsa.mergeSortByValue(records)"),
p2("'Name (Merge Sort - D&C)'  → m_dsa.mergeSortByName(records)"),
h("Comparison: Bubble vs Selection"),
p("Both O(n²) time.  Key difference: Selection Sort makes at most n-1 swaps."),
p("Bubble Sort can make up to n²/2 swaps. For write-expensive memory: Selection Sort wins."),
p("For nearly-sorted data: Bubble Sort with early-exit is Ω(n). Selection is always Θ(n²)."),
])

# ── SLIDE 10: BUBBLE SORT DETAILED ───────────────────────────
sl = slide()
title(sl,"Bubble Sort — Full Explanation with Trace")
body(sl,[
h("Algorithm Description"),
p("Bubble Sort compares adjacent pairs of elements and swaps them if they are in the wrong order."),
p("After each complete pass through the array, the largest unsorted element 'bubbles' to its"),
p2("correct position at the end. The inner loop range shrinks by 1 after each outer pass."),
h("Step-by-Step Trace  —  Input: [64, 34, 25, 12, 22]  (sort ascending by ID)"),
p("Pass 1: Compare 64>34 → swap: [34,64,25,12,22]"),
p2("        Compare 64>25 → swap: [34,25,64,12,22]"),
p2("        Compare 64>12 → swap: [34,25,12,64,22]"),
p2("        Compare 64>22 → swap: [34,25,12,22,64]   ← 64 is in final position"),
p("Pass 2: Compare 34>25 → swap: [25,34,12,22,64]"),
p2("        Compare 34>12 → swap: [25,12,34,22,64]"),
p2("        Compare 34>22 → swap: [25,12,22,34,64]   ← 34 in final position"),
p("Pass 3: Compare 25>12 → swap: [12,25,22,34,64]"),
p2("        Compare 25>22 → swap: [12,22,25,34,64]   ← 25 in final position"),
p("Pass 4: Compare 12<22 → no swap: [12,22,25,34,64] ← SORTED"),
h("Code from dsaengine.cpp — bubbleSortById()"),
code("void DSAEngine::bubbleSortById(vector<AssetRecord> &assets) {"),
code("    int n = (int)assets.size();"),
code("    for (int i = 0; i < n-1; i++) {           // outer: n-1 passes"),
code("        for (int j = 0; j < n-i-1; j++) {     // inner: shrinks each pass"),
code("            if (assets[j].id > assets[j+1].id) {"),
code("                AssetRecord tmp = assets[j];   // swap"),
code("                assets[j] = assets[j+1];"),
code("                assets[j+1] = tmp;"),
code("            }  }  }  }"),
h("Time Complexity Derivation"),
p("Inner loop runs: (n-1) + (n-2) + ... + 2 + 1 = n(n-1)/2 iterations"),
p("n(n-1)/2 = (n²-n)/2.  Drop low-order term n and constant 1/2 → O(n²)"),
p("Space: only one temp variable 'tmp' → O(1) extra space. In-place sort."),
])

# ── SLIDE 11: SELECTION SORT ──────────────────────────────────
sl = slide()
title(sl,"Selection Sort — Full Explanation with Code")
body(sl,[
h("Algorithm Description"),
p("Selection Sort divides the array into a sorted portion (left) and unsorted portion (right)."),
p("In each pass, it finds the MINIMUM element in the unsorted portion and swaps it"),
p2("into the first position of the unsorted portion. The sorted portion grows by 1 each pass."),
p("Key insight: at most n-1 swaps total, regardless of input."),
h("Step-by-Step Trace  —  Input: [laptop, desk, chair, projector]  (sort by name)"),
p("Pass 1: Unsorted=[laptop,desk,chair,projector]. Min=chair at index 2."),
p2("        Swap chair↔laptop: [chair, desk, laptop, projector]"),
p("Pass 2: Unsorted=[desk,laptop,projector]. Min=desk at index 1. No swap needed."),
p2("        Result: [chair, desk, laptop, projector]"),
p("Pass 3: Unsorted=[laptop,projector]. Min=laptop. No swap needed."),
p2("        Result: [chair, desk, laptop, projector]  ← SORTED"),
h("Code from dsaengine.cpp — selectionSortByName()"),
code("void DSAEngine::selectionSortByName(vector<AssetRecord> &assets) {"),
code("    int n = (int)assets.size();"),
code("    for (int i = 0; i < n-1; i++) {"),
code("        int minIdx = i;                         // assume current is min"),
code("        for (int j = i+1; j < n; j++) {"),
code("            if (assets[j].name < assets[minIdx].name)"),
code("                minIdx = j;                     // found smaller element"),
code("        }"),
code("        if (minIdx != i) {                      // only swap if needed"),
code("            AssetRecord tmp = assets[i];"),
code("            assets[i] = assets[minIdx];"),
code("            assets[minIdx] = tmp;"),
code("        }  }  }"),
h("Comparison: Bubble Sort vs Selection Sort"),
p("Swaps:     Bubble = up to n²/2.    Selection = exactly n-1 (at most)"),
p("Comparisons: Both = n(n-1)/2 = O(n²)"),
p("Stability:  Bubble Sort is STABLE (equal elements keep original order)."),
p2("            Selection Sort is NOT stable by default."),
p("Use Selection when swap cost is high (e.g., swapping large objects in memory)."),
h("Where Used in Project"),
p("'Name (Selection Sort)' dropdown option → calls m_dsa.selectionSortByName()"),
p("'Location (Selection Sort)' → calls m_dsa.selectionSortByLocation()"),
p("Both in assetwindow.cpp → sortAssets() method → refreshAllTabs() called after"),
])

# ── SLIDE 12: LINEAR SEARCH ───────────────────────────────────
sl = slide()
title(sl,"Linear Search — Oracle SQL Implementation")
body(sl,[
h("Algorithm Description"),
p("Linear Search scans every element from start to end until the target is found or"),
p2("the entire list is exhausted. No assumption about ordering of elements."),
p("Time: O(n) average and worst case.  Best case: O(1) if target is first element."),
h("Implementation in Our Project — SecurityCheckWindow::searchItem()"),
p("The Oracle SQL query uses LIKE operator which performs a linear scan of the table:"),
code("SELECT si.ITEM_ID, u.FULL_NAME, u.STUDENT_ID, si.ITEM_NAME,"),
code("       si.CATEGORY, si.BRAND, si.STATUS"),
code("FROM   STUDENT_ITEMS si"),
code("JOIN   USERS u ON si.STUDENT_ID = u.USER_ID"),
code("WHERE  LOWER(si.SERIAL_NUMBER) = LOWER(:serial)"),
code("    OR LOWER(si.ITEM_NAME)    LIKE LOWER(:likeSerial)"),
code("    OR LOWER(si.BRAND)        LIKE LOWER(:likeSerial)"),
p("Oracle evaluates the WHERE clause for EVERY row → O(n) scan"),
p("For a table with 1000 student items: up to 1000 comparisons"),
h("Our Improvement: BST Pre-Check Before SQL"),
p("Before the SQL query, we run BST search on exact serial number match:"),
code("bool bstHit = m_dsa.bstSearch(serial.toLower().toStdString(), bstItemId);"),
p("BST search = O(log n) ≈ 10 comparisons for 1000 items (vs 1000 for linear)"),
p("The blue info bar in SecurityCheckWindow shows this comparison live:"),
p2("'BST: FOUND in O(log n) ≈ 10 comparisons vs O(n) = 1000 for linear scan'"),
h("Linear Search Justified When:"),
p("Data is unsorted (no BST available)"),
p("Dataset is very small (< 20 items) — overhead of building BST not worth it"),
p("Searching by multiple fields simultaneously (name OR brand — no single BST key)"),
h("Oracle Indexing Note"),
p("Oracle can add B-tree index on SERIAL_NUMBER column to speed up = comparison"),
p("But LIKE with wildcard (%) cannot use standard index — always linear scan"),
p("Our BST completely bypasses this limitation for exact serial number lookups"),
])

# ── SLIDE 13: CH3 DIVIDER ─────────────────────────────────────
sl = slide()
title(sl,"Chapter 3 — Linked Lists")
body(sl,[
h("Chapter Overview"),
p("A Linked List is a linear data structure where elements (nodes) are stored at"),
p2("non-contiguous memory locations. Each node contains data and a pointer to the next node."),
p("Types covered: Singly linked list (we implement this), doubly linked list, circular list."),
h("Why Linked Lists Matter"),
p("Arrays have fixed size — you must know capacity upfront."),
p("Linked Lists grow and shrink dynamically — memory allocated only when needed."),
p("Insert/delete at head or tail: O(1) with proper pointers."),
p("No wasted capacity (unlike std::vector which may allocate 2× needed space)."),
h("Our Implementation"),
p("We replaced std::queue<string> (which wraps std::deque with block allocation)"),
p2("with a custom singly-linked list: LLNode struct + head/tail pointers."),
p("This demonstrates Ch.3 material directly and gives same O(1) enqueue/dequeue."),
h("Singly vs Doubly vs Circular — Why We Chose Singly"),
p("Singly: each node has one 'next' pointer. Enough for FIFO queue (head=dequeue, tail=enqueue)."),
p("Doubly: each node has 'next' AND 'prev'. Needed for bidirectional traversal or O(1) remove."),
p("Circular: tail->next points back to head. Used for round-robin scheduling."),
p("Our use case is a simple audit log queue — singly linked is sufficient and simpler."),
h("Dynamic Memory in C++"),
p("Each new LLNode is created with 'new LLNode(action)' — heap allocation."),
p("Must be freed with 'delete' — done in DSAEngine destructor:"),
code("LLNode *cur = m_llHead;"),
code("while (cur) { LLNode *next = cur->next; delete cur; cur = next; }"),
p("This prevents memory leaks. Valgrind would show zero leaks if run."),
])

# ── SLIDE 14: LL STRUCT & DIAGRAM ────────────────────────────
sl = slide()
title(sl,"Linked List — LLNode Structure and Diagram")
body(sl,[
h("LLNode Struct — from dsaengine.h"),
code("struct LLNode {"),
code("    std::string data;        // the action string e.g. 'ADD: Laptop'"),
code("    LLNode *next = nullptr;  // pointer to next node (null at tail)"),
code("    explicit LLNode(const std::string &d) : data(d) {}"),
code("};"),
h("DSAEngine Private Members"),
code("LLNode *m_llHead = nullptr;   // points to first node (dequeue here)"),
code("LLNode *m_llTail = nullptr;   // points to last node (enqueue here)"),
code("int     m_llCount = 0;        // tracks size without traversal"),
h("Visual Representation — After 3 Actions"),
p("m_llHead                                               m_llTail"),
p("    |                                                       |"),
p("    v                                                       v"),
p("[ADD:Laptop] --next--> [EDIT:Chair] --next--> [DELETE:Desk] --next--> nullptr"),
p(""),
p("Enqueue 'ADD:Projector' → new node appended at tail:"),
p("[ADD:Laptop] --next--> [EDIT:Chair] --next--> [DELETE:Desk] --next--> [ADD:Projector] → null"),
p("m_llTail now points to [ADD:Projector]. Time: O(1)"),
p(""),
p("Dequeue → remove from head:"),
p("m_llHead advances to [EDIT:Chair]. [ADD:Laptop] deleted. Time: O(1)"),
h("LLContents() — for Display/Report"),
code("std::string DSAEngine::llContents() const {"),
code("    std::string result = 'Action Log (head to tail):\\n';"),
code("    LLNode *cur = m_llHead;"),
code("    int i = 1;"),
code("    while (cur) {"),
code("        result += '  ' + to_string(i++) + '. ' + cur->data + '\\n';"),
code("        cur = cur->next;"),
code("    }"),
code("    return result;"),
code("}"),
h("Where enqueueAction() is Called in the Project"),
p("assetwindow.cpp addAsset():    m_dsa.enqueueAction('ADD: ' + snap.assetName)"),
p("assetwindow.cpp editAsset():   m_dsa.enqueueAction('EDIT: ' + oldName.toStdString())"),
p("assetwindow.cpp deleteBy*():   m_dsa.enqueueAction('DELETE: ' + snap.assetName)"),
])

# ── SLIDE 15: LL CODE FULL ────────────────────────────────────
sl = slide()
title(sl,"Linked List — Complete Code (dsaengine.cpp)")
body(sl,[
h("llEnqueue — Append at Tail  O(1)"),
code("void DSAEngine::llEnqueue(const std::string &action) {"),
code("    LLNode *node = new LLNode(action);  // create new node on heap"),
code("    if (!m_llTail) {                    // list is empty"),
code("        m_llHead = m_llTail = node;     // both head and tail point to it"),
code("    } else {"),
code("        m_llTail->next = node;          // link current tail to new node"),
code("        m_llTail = node;               // advance tail pointer"),
code("    }"),
code("    ++m_llCount;"),
code("}"),
h("llDequeue — Remove from Head  O(1)"),
code("std::string DSAEngine::llDequeue() {"),
code("    if (!m_llHead) return '';           // empty list"),
code("    std::string val = m_llHead->data;   // save the data"),
code("    LLNode *old = m_llHead;             // save pointer to free"),
code("    m_llHead = m_llHead->next;          // advance head"),
code("    if (!m_llHead) m_llTail = nullptr;  // list is now empty"),
code("    delete old;                         // free the node"),
code("    --m_llCount;"),
code("    return val;"),
code("}"),
h("Legacy Compatibility Aliases in dsaengine.h"),
code("void enqueueAction(const std::string &a) { llEnqueue(a); }"),
code("std::string dequeueAction()              { return llDequeue(); }"),
code("bool isQueueEmpty() const               { return llIsEmpty(); }"),
code("int  queueSize()    const               { return llSize(); }"),
p("These aliases ensure that older code calling enqueueAction() still works"),
p2("while the actual implementation uses the new linked list internally."),
h("Complexity Summary"),
p("llEnqueue: O(1) — tail pointer makes append constant time"),
p("llDequeue: O(1) — head pointer makes remove constant time"),
p("llSize:    O(1) — m_llCount tracked explicitly"),
p("llContents: O(n) — must visit every node to build string"),
p("Destructor: O(n) — must delete every node to prevent memory leak"),
])

# ── SLIDE 16: CH4 DIVIDER ─────────────────────────────────────
sl = slide()
title(sl,"Chapter 4 — Stacks and Queues")
body(sl,[
h("Chapter Overview"),
p("Stack: LIFO (Last In, First Out). Like a stack of plates — add and remove from the top."),
p("Queue: FIFO (First In, First Out). Like a line of people — join at back, leave from front."),
p("Both can be implemented with arrays or linked lists. Our project uses both."),
h("Stack Use in Our Project — Undo/Redo System"),
p("The undo/redo system in Asset Manager uses two stacks: m_undoStack and m_redoStack."),
p("Every add/edit/delete operation pushes an AssetSnapshot onto m_undoStack."),
p("Clicking Undo pops from m_undoStack, reverses the DB operation, pushes to m_redoStack."),
p("Clicking Redo pops from m_redoStack, re-applies the DB operation, pushes to m_undoStack."),
h("Queue Use in Our Project — Action Log"),
p("Every asset operation is also logged to a FIFO queue (our custom linked list)."),
p("Purpose: audit trail — first action added is first in the log (chronological order)."),
p("We deliberately implemented this as a custom linked list (not std::queue)"),
p2("to demonstrate Chapter 3 (linked list) integrated with Chapter 4 (queue ADT)."),
h("AssetSnapshot — What Gets Pushed on the Stack"),
p("assetId:      the Oracle ASSET_ID of the affected row"),
p("assetName:    name of the asset at time of action"),
p("category:     category string (e.g. IT_EQUIPMENT)"),
p("condition:    GOOD|BROKEN|UNDER_MAINTENANCE|DECOMMISSIONED"),
p("serialNumber: the serial number string"),
p("purchaseValue: double precision monetary value"),
p("action:       ActionType enum — ADD_ASSET | DELETE_ASSET | EDIT_ASSET"),
h("MAX_STACK_SIZE = 20"),
p("Stack is capped at 20 entries. If a 21st entry is pushed, the oldest (bottom) is removed."),
p("This prevents unbounded memory growth in a long session."),
p("Implementation: drain into temp stack, pop oldest, refill. O(n) but only at size 20."),
])

# ── SLIDE 17: STACK CODE ──────────────────────────────────────
sl = slide()
title(sl,"Stack — Complete Code and Undo/Redo Flow")
body(sl,[
h("pushUndo — from dsaengine.cpp"),
code("void DSAEngine::pushUndo(const AssetSnapshot &snap) {"),
code("    if ((int)m_undoStack.size() >= MAX_STACK_SIZE) {"),
code("        // drain to temp, pop oldest, refill"),
code("        std::stack<AssetSnapshot> temp;"),
code("        while (m_undoStack.size() > 1) {"),
code("            temp.push(m_undoStack.top()); m_undoStack.pop(); }"),
code("        m_undoStack.pop();  // remove oldest"),
code("        while (!temp.empty()) {"),
code("            m_undoStack.push(temp.top()); temp.pop(); }"),
code("    }"),
code("    m_undoStack.push(snap);  // O(1)"),
code("}"),
h("undoAction — from assetwindow.cpp (shows how stack integrates with Oracle)"),
code("void AssetWindow::undoAction() {"),
code("    AssetSnapshot snap = m_dsa.popUndo();"),
code("    if (snap.action == ActionType::ADD_ASSET) {"),
code("        // Undo an add: delete the row from Oracle"),
code("        QSqlQuery q; q.prepare('DELETE FROM ASSETS WHERE asset_id=:id');"),
code("        q.bindValue(':id', snap.assetId); q.exec();"),
code("        m_dsa.pushRedo(snap);"),
code("    } else if (snap.action == ActionType::DELETE_ASSET) {"),
code("        // Undo a delete: re-insert into Oracle"),
code("        QSqlQuery q; q.prepare('INSERT INTO ASSETS ...'); /* bind all fields */"),
code("        m_dsa.pushRedo(snap);"),
code("    } else if (snap.action == ActionType::EDIT_ASSET) {"),
code("        // Undo an edit: restore previous values"),
code("        QSqlQuery q; q.prepare('UPDATE ASSETS SET ... WHERE asset_id=:id');"),
code("        m_dsa.pushRedo(snap);"),
code("    }"),
code("    updateStackLabel(stackLabel, m_dsa, undoBtn, redoBtn);"),
code("    loadAssets();  // refresh table"),
code("}"),
h("Stack Label Update"),
code("static void updateStackLabel(QLabel *lbl, DSAEngine &dsa,"),
code("                              QPushButton *undoBtn, QPushButton *redoBtn) {"),
code("    lbl->setText(QString('Undo: %1  |  Redo: %2')"),
code("                 .arg(dsa.undoSize()).arg(dsa.redoSize()));"),
code("    undoBtn->setEnabled(dsa.canUndo());"),
code("    redoBtn->setEnabled(dsa.canRedo());"),
code("}"),
h("Complexity"),
p("pushUndo: O(1) normally, O(n) only at MAX_STACK_SIZE=20 — bounded constant"),
p("popUndo:  O(1) — std::stack::top() and pop() are both O(1)"),
p("Space:    O(20) = O(1) bounded — never exceeds 20 AssetSnapshot objects"),
])

# ── SLIDE 18: CH5 DIVIDER ─────────────────────────────────────
sl = slide()
title(sl,"Chapter 5 — Recursion")
body(sl,[
h("Chapter Overview"),
p("Recursion is a programming technique where a function solves a problem by calling itself"),
p2("on smaller subproblems. Every recursive function must have:"),
p("1. BASE CASE: the condition that stops the recursion (no further self-call)"),
p("2. RECURSIVE CASE: the step that calls the function with a smaller/simpler input"),
p("3. PROGRESS: each recursive call must move TOWARDS the base case"),
h("Types of Recursion"),
p("Tail Recursion: the recursive call is the LAST operation in the function"),
p("Nested Recursion: arguments to recursive call are themselves recursive calls"),
p("Backtracking: tries all possibilities, undoes choices that lead to dead ends"),
h("Recursion in Our Project — 5 Uses in dsaengine.cpp"),
p("bstInsertHelper()  — navigates left/right until empty slot, creates node"),
p("bstSearchHelper()  — navigates left/right until match found or null"),
p("bstClearHelper()   — post-order: delete left subtree, right subtree, then node"),
p("bstHeightHelper()  — returns max(height(left), height(right)) + 1"),
p("graphDFS() lambda  — visits node, recurses into each unvisited neighbour"),
h("Connection Between Recursion and the Call Stack"),
p("Each recursive call is pushed onto the program's call stack."),
p("For BST with height h: the call stack depth = h = O(log n) for balanced tree."),
p("For DFS on graph with V nodes: call stack depth = V in worst case."),
p("Stack overflow risk: for very deep recursion (n > ~10,000 on most systems)."),
p("Our trees are small (few hundred items) so no risk of stack overflow."),
h("Recursion vs Iteration"),
p("All recursive algorithms can be converted to iterative using an explicit stack."),
p("BFS is iterative (uses std::queue). DFS can be iterative with std::stack."),
p("We chose recursive DFS to explicitly demonstrate Chapter 5 recursion."),
p("mergeSortHelperByValue() is also recursive — demonstrates D&C recursion (Ch.9)."),
])

# ── SLIDE 19: RECURSION CODE ──────────────────────────────────
sl = slide()
title(sl,"Recursion — BST Insert and Clear Code")
body(sl,[
h("bstInsertHelper — Recursive BST Insert"),
code("BSTNode* DSAEngine::bstInsertHelper("),
code("        BSTNode *node, const std::string &serial, int itemId) {"),
code("    // BASE CASE: found an empty slot"),
code("    if (!node)"),
code("        return new BSTNode(serial, itemId);"),
code("    // RECURSIVE CASE: go left or right"),
code("    if (serial < node->serial)"),
code("        node->left  = bstInsertHelper(node->left,  serial, itemId);"),
code("    else if (serial > node->serial)"),
code("        node->right = bstInsertHelper(node->right, serial, itemId);"),
code("    // duplicate: ignore"),
code("    return node;"),
code("}"),
h("Call Stack Trace — Inserting 'SN-035' into BST rooted at 'SN-050'"),
p("Call 1: bstInsertHelper(root='SN-050', 'SN-035', 5)"),
p2("  SN-035 < SN-050 → recurse left"),
p("Call 2: bstInsertHelper(node='SN-020', 'SN-035', 5)"),
p2("  SN-035 > SN-020 → recurse right"),
p("Call 3: bstInsertHelper(node=null, 'SN-035', 5)"),
p2("  node is null → BASE CASE → return new BSTNode('SN-035', 5)"),
p("Call 2 returns: root->left->right = new node. Call 1 returns: root unchanged."),
h("bstClearHelper — Post-Order Recursive Delete (prevents memory leak)"),
code("void DSAEngine::bstClearHelper(BSTNode *node) {"),
code("    if (!node) return;              // BASE CASE: null = nothing to delete"),
code("    bstClearHelper(node->left);     // delete entire left subtree first"),
code("    bstClearHelper(node->right);    // delete entire right subtree"),
code("    delete node;                    // THEN delete current node"),
code("}"),
p("Post-order (left→right→root) ensures children are deleted before parent."),
p("Deleting parent first would lose pointers to children → memory leak."),
h("bstHeightHelper — Returns Height of Tree"),
code("int DSAEngine::bstHeightHelper(BSTNode *node) const {"),
code("    if (!node) return 0;            // BASE CASE: empty = height 0"),
code("    int l = bstHeightHelper(node->left);   // height of left subtree"),
code("    int r = bstHeightHelper(node->right);  // height of right subtree"),
code("    return 1 + std::max(l, r);      // current node + taller child"),
code("}"),
p("For a balanced BST with n nodes: height = floor(log₂(n)) = O(log n)"),
p("Displayed in SecurityCheckWindow blue bar: 'Height: X | O(log n) ≈ X comparisons'"),
])

# ── SLIDE 20: CH6 DIVIDER ─────────────────────────────────────
sl = slide()
title(sl,"Chapter 6 — Trees and Binary Search Tree (BST)")
body(sl,[
h("Chapter Overview"),
p("Trees are hierarchical non-linear data structures. A Binary Tree: each node has"),
p2("at most 2 children (left and right). BST adds the ordering property."),
h("BST Property — The Most Important Rule"),
p("For every node N in the BST:"),
p("  ALL values in N's LEFT subtree are LESS THAN N's value"),
p("  ALL values in N's RIGHT subtree are GREATER THAN N's value"),
p("This property holds recursively for every subtree in the entire tree."),
p("Consequence: in-order traversal (left→root→right) gives elements in SORTED order."),
h("BST Operations and Complexity"),
p("Insert:    Compare with root, go left if smaller, right if larger. Recurse. O(log n) avg."),
p("Search:    Same navigation — if found return true, if null return false. O(log n) avg."),
p("Delete:    Find node, handle 3 cases: no child, one child, two children. O(log n) avg."),
p("In-order:  Left subtree → visit root → right subtree. Gives sorted output. O(n)."),
p("Height:    Recursively max(height(left), height(right)) + 1. O(n)."),
h("Our Use Case — Serial Number Index for Security Check"),
p("When SecurityCheckWindow opens, loadSerialsBST() queries all STUDENT_ITEMS serial"),
p2("numbers from Oracle and inserts them into the BST (one bstInsert per serial)."),
p("Building BST from n serials: O(n log n) — n insertions each costing O(log n)."),
p("Each security scan: O(log n) — BST search instead of O(n) SQL linear scan."),
p("For 500 registered items: BST built in ~500×9 = ~4500 ops. Each search: ~9 ops."),
h("BST vs Hash Table Trade-offs"),
p("Hash Table: O(1) average search but loses element ordering."),
p("BST:        O(log n) search BUT gives sorted in-order traversal for free."),
p("Choice: BST is better here because we can also produce a sorted serial report"),
p2("via bstInorder() — a feature a hash table cannot provide."),
h("Worst Case BST — Degenerate Tree"),
p("If serials are inserted in alphabetical order: SN-001, SN-002, SN-003 ..."),
p("The BST degenerates to a linked list: every node only has a right child."),
p("Height becomes n instead of log n. Search becomes O(n) not O(log n)."),
p("Prevention: use AVL tree or Red-Black tree (self-balancing). Not in this project scope."),
])

# ── SLIDE 21: BST FULL CODE ───────────────────────────────────
sl = slide()
title(sl,"BST — Complete Insert and Search Code")
body(sl,[
h("Entry Point — bstInsert() called by loadSerialsBST()"),
code("void DSAEngine::bstInsert(const std::string &serial, int itemId) {"),
code("    m_bstRoot = bstInsertHelper(m_bstRoot, serial, itemId);"),
code("    ++m_bstCount;"),
code("}"),
h("Recursive Insert — bstInsertHelper()"),
code("BSTNode* DSAEngine::bstInsertHelper("),
code("        BSTNode *node, const std::string &serial, int itemId) {"),
code("    if (!node) return new BSTNode(serial, itemId); // base case"),
code("    if (serial < node->serial)"),
code("        node->left = bstInsertHelper(node->left, serial, itemId);"),
code("    else if (serial > node->serial)"),
code("        node->right = bstInsertHelper(node->right, serial, itemId);"),
code("    // equal: duplicate serial — ignore"),
code("    return node;"),
code("}"),
h("Entry Point — bstSearch() called by searchItem() in SecurityCheckWindow"),
code("bool DSAEngine::bstSearch(const std::string &serial, int &outItemId) const {"),
code("    return bstSearchHelper(m_bstRoot, serial, outItemId);"),
code("}"),
h("Recursive Search — bstSearchHelper()"),
code("bool DSAEngine::bstSearchHelper(BSTNode *node, const std::string &serial,"),
code("                                  int &outId) const {"),
code("    if (!node) return false;              // not found (base case 1)"),
code("    if (serial == node->serial) {         // found (base case 2)"),
code("        outId = node->itemId; return true;"),
code("    }"),
code("    if (serial < node->serial)"),
code("        return bstSearchHelper(node->left,  serial, outId);"),
code("    return bstSearchHelper(node->right, serial, outId);"),
code("}"),
h("SecurityCheckWindow — Using BST Before DB Query"),
code("void SecurityCheckWindow::searchItem() {"),
code("    int bstItemId = -1;"),
code("    bool bstHit = m_dsa.bstSearch(serial.toLower().toStdString(), bstItemId);"),
code("    int n = m_dsa.bstSize();"),
code("    int logN = (n > 0) ? (int)ceil(log2(n + 1)) : 0;"),
code("    if (bstHit)"),
code("        bstLabel->setText(QString('BST: FOUND in O(log n) ≈ %1 comparisons'"),
code("                                  ' vs O(n)=%2 linear').arg(logN).arg(n));"),
code("    // ... then run Oracle SQL for full record details"),
code("}"),
])

# ── SLIDE 22: CH7 DIVIDER ─────────────────────────────────────
sl = slide()
title(sl,"Chapter 7 — Graphs: BFS and DFS")
body(sl,[
h("Chapter Overview"),
p("A graph G = (V, E) where V = set of vertices (nodes) and E = set of edges (connections)."),
p("Directed graph: edges have direction (A→B ≠ B→A)."),
p("Undirected graph: edges are bidirectional (A—B same as B—A). Our campus graph is undirected."),
p("Weighted graph: edges have weights (distances/costs). Our graph is unweighted."),
h("Graph Representations"),
p("Adjacency Matrix: V×V 2D array. matrix[i][j]=1 if edge exists. Space O(V²)."),
p("Adjacency List: map from node to list of neighbours. Space O(V+E). Better for sparse graphs."),
p("We use adjacency list:"),
p2("std::unordered_map<std::string, std::vector<std::string>> m_graph"),
p2("Key = building name. Value = list of directly connected buildings."),
h("Our Campus Graph — DBU Buildings"),
p("10 nodes (buildings): Main Gate, Library, Admin Block, College of Computing,"),
p2("Lab Block, Cafeteria, Sports Complex, Dormitory A, Dormitory B, Medical Center"),
p("12 undirected edges (paths connecting buildings)"),
p("Graph is connected: every building is reachable from every other building."),
h("Graph Traversal Algorithms"),
p("BFS (Breadth-First Search): explore level by level using a QUEUE."),
p2("Guarantees shortest path in unweighted graph. O(V+E) time."),
p("DFS (Depth-First Search): explore as deep as possible using RECURSION or explicit STACK."),
p2("Useful for connectivity, cycle detection, topological sort. O(V+E) time."),
h("Real-World Application in Our Project"),
p("CampusGraphWindow: security officer wants shortest path from Main Gate to Medical Center"),
p2("(e.g., to escort a student with an emergency). BFS gives the minimum-hop route."),
p("DFS: verify all buildings are reachable from Admin Block (connectivity check)."),
p("Both algorithms shown with live output in the Campus Graph window."),
])

# ── SLIDE 23: GRAPH ADJ LIST & INIT ──────────────────────────
sl = slide()
title(sl,"Graph — Adjacency List and graphInit()")
body(sl,[
h("graphAddEdge and graphInit — dsaengine.cpp"),
code("void DSAEngine::graphAddEdge(const std::string &u, const std::string &v) {"),
code("    m_graph[u].push_back(v);   // undirected: add both directions"),
code("    m_graph[v].push_back(u);"),
code("}"),
code(""),
code("void DSAEngine::graphInit() {"),
code("    m_graph.clear();"),
code("    graphAddEdge('Main Gate',             'Library');"),
code("    graphAddEdge('Main Gate',             'Admin Block');"),
code("    graphAddEdge('Library',               'College of Computing');"),
code("    graphAddEdge('Library',               'Cafeteria');"),
code("    graphAddEdge('Admin Block',           'College of Computing');"),
code("    graphAddEdge('Admin Block',           'Lab Block');"),
code("    graphAddEdge('College of Computing',  'Lab Block');"),
code("    graphAddEdge('Cafeteria',             'Sports Complex');"),
code("    graphAddEdge('Cafeteria',             'Dormitory A');"),
code("    graphAddEdge('Sports Complex',        'Dormitory B');"),
code("    graphAddEdge('Dormitory A',           'Medical Center');"),
code("    graphAddEdge('Dormitory B',           'Medical Center');"),
code("}"),
h("Resulting Adjacency List"),
p("Main Gate            → Library, Admin Block"),
p("Library              → Main Gate, College of Computing, Cafeteria"),
p("Admin Block          → Main Gate, College of Computing, Lab Block"),
p("College of Computing → Library, Admin Block, Lab Block"),
p("Lab Block            → Admin Block, College of Computing"),
p("Cafeteria            → Library, Sports Complex, Dormitory A"),
p("Sports Complex       → Cafeteria, Dormitory B"),
p("Dormitory A          → Cafeteria, Medical Center"),
p("Dormitory B          → Sports Complex, Medical Center"),
p("Medical Center       → Dormitory A, Dormitory B"),
h("Space Complexity"),
p("Adjacency list: O(V+E) = O(10+12) = O(22) — very efficient for sparse graph."),
p("Adjacency matrix would need 10×10=100 entries (most would be 0)."),
])

# ── SLIDE 24: BFS FULL CODE ───────────────────────────────────
sl = slide()
title(sl,"Graph — BFS Shortest Path: Full Code and Trace")
body(sl,[
h("graphBFS — dsaengine.cpp"),
code("std::vector<std::string> DSAEngine::graphBFS("),
code("        const std::string &start, const std::string &end) const {"),
code("    std::unordered_map<std::string,std::string> parent; // child→parent map"),
code("    std::queue<std::string>                     bfsQ;"),
code("    std::unordered_set<std::string>             visited;"),
code(""),
code("    bfsQ.push(start);"),
code("    visited.insert(start);"),
code("    parent[start] = '';"),
code(""),
code("    while (!bfsQ.empty()) {"),
code("        std::string node = bfsQ.front(); bfsQ.pop();"),
code("        if (node == end) {"),
code("            // Reconstruct path by walking parent pointers"),
code("            std::vector<std::string> path;"),
code("            for (std::string cur=end; cur!=''; cur=parent[cur])"),
code("                path.push_back(cur);"),
code("            std::reverse(path.begin(), path.end());"),
code("            return path;"),
code("        }"),
code("        for (const std::string &nb : m_graph.at(node))"),
code("            if (!visited.count(nb)) {"),
code("                visited.insert(nb); parent[nb]=node; bfsQ.push(nb);"),
code("            }"),
code("    }"),
code("    return {};  // no path found"),
code("}"),
h("BFS Trace — 'Main Gate' to 'Medical Center'"),
p("Initial: queue=[Main Gate], visited={Main Gate}, parent={Main Gate:''}"),
p("Dequeue Main Gate. Neighbours: Library, Admin Block (both unvisited)"),
p2("Enqueue Library (parent=Main Gate), Admin Block (parent=Main Gate)"),
p("Dequeue Library. Neighbours: College of Computing, Cafeteria (unvisited)"),
p2("Enqueue College of Computing, Cafeteria"),
p("Dequeue Admin Block. Neighbours: College of Computing (visited), Lab Block"),
p2("Enqueue Lab Block"),
p("Dequeue College of Computing. Neighbours: Lab Block (visited)"),
p("Dequeue Cafeteria. Neighbours: Sports Complex, Dormitory A"),
p2("Enqueue Sports Complex (parent=Cafeteria), Dormitory A (parent=Cafeteria)"),
p("Dequeue Lab Block. No new neighbours."),
p("Dequeue Sports Complex. Enqueue Dormitory B (parent=Sports Complex)"),
p("Dequeue Dormitory A. Enqueue Medical Center (parent=Dormitory A)"),
p("Dequeue Dormitory B. Medical Center already enqueued."),
p("Dequeue Medical Center. node==end! Reconstruct path:"),
p2("Medical Center ← Dormitory A ← Cafeteria ← Library ← Main Gate"),
p2("Reversed: Main Gate → Library → Cafeteria → Dormitory A → Medical Center"),
p("Result: 4 hops (shortest possible path between these buildings)"),
])

# ── SLIDE 25: DFS CODE ────────────────────────────────────────
sl = slide()
title(sl,"Graph — DFS Traversal: Full Code and Explanation")
body(sl,[
h("graphDFS — dsaengine.cpp  (Recursive Implementation)"),
code("std::vector<std::string> DSAEngine::graphDFS("),
code("        const std::string &start) const {"),
code("    std::vector<std::string>        visited;   // output: visit order"),
code("    std::unordered_set<std::string> seen;      // tracks visited nodes"),
code(""),
code("    // Recursive lambda — captures visited/seen by reference"),
code("    std::function<void(const std::string&)> dfs ="),
code("        [&](const std::string &node) {"),
code("            seen.insert(node);            // mark visited BEFORE recursing"),
code("            visited.push_back(node);      // record visit order"),
code("            auto it = m_graph.find(node);"),
code("            if (it == m_graph.end()) return;"),
code("            for (const std::string &nb : it->second)"),
code("                if (!seen.count(nb))"),
code("                    dfs(nb);              // RECURSIVE: explore deeper first"),
code("        };"),
code(""),
code("    if (m_graph.count(start)) dfs(start);"),
code("    return visited;"),
code("}"),
h("DFS Trace — Starting from 'College of Computing'"),
p("Visit College of Computing. Neighbours: Library, Admin Block, Lab Block"),
p("Recurse into Library. Neighbours: Main Gate, College of Computing(seen), Cafeteria"),
p("  Recurse into Main Gate. Neighbours: Library(seen), Admin Block"),
p("    Recurse into Admin Block. Neighbours: Main Gate(seen), College of Computing(seen), Lab Block"),
p("      Recurse into Lab Block. All neighbours seen. Backtrack."),
p("    Backtrack to Admin Block. Done. Backtrack to Main Gate. Done."),
p("  Back to Library. Recurse into Cafeteria."),
p("    Recurse into Sports Complex → Dormitory B → Medical Center → Dormitory A"),
p2("    All visited."),
p("Result order: College of Computing, Library, Main Gate, Admin Block, Lab Block,"),
p2("  Cafeteria, Sports Complex, Dormitory B, Medical Center, Dormitory A"),
h("Key Differences: BFS vs DFS"),
p("BFS uses a queue (FIFO) — explores level by level — guarantees shortest path"),
p("DFS uses recursion (call stack) — explores depth first — detects connectivity"),
p("BFS: better for 'find closest' problems.  DFS: better for 'visit all' problems."),
p("Both have the same time complexity: O(V+E)"),
])

# ── SLIDE 26: CH8 DIVIDER ─────────────────────────────────────
sl = slide()
title(sl,"Chapter 8 — Advanced Sorting and Searching")
body(sl,[
h("Chapter Overview"),
p("Chapter 8 introduces sorting algorithms that are more efficient than O(n²)."),
p("Algorithms: Shell Sort (not implemented), Quick Sort (theory), Merge Sort (implemented),"),
p2("Heap Sort (theory). Searching: Hashing (BST provides similar benefit)."),
h("Why O(n²) Sorting is Insufficient"),
p("For n=100 assets:  Bubble Sort = 4,950 comparisons. Merge Sort = 665 comparisons."),
p("For n=1,000 assets: Bubble = 499,500. Merge = 9,966. Difference: 50× faster."),
p("For n=10,000 assets: Bubble = 50,000,000. Merge = 133,000. Difference: 375× faster."),
p("Lesson: algorithm choice matters enormously as data grows."),
h("Merge Sort — Key Properties"),
p("Strategy: Divide & Conquer (directly from Chapter 9 — connects two chapters)."),
p("Time: O(n log n) — SAME in best, average, AND worst case."),
p("Space: O(n) — needs auxiliary memory for merge step (unlike in-place sorts)."),
p("Stability: YES — equal elements keep their original relative order."),
h("Why Merge Sort Over Quick Sort"),
p("Quick Sort: O(n log n) average but O(n²) WORST CASE (bad pivot selection)."),
p("Merge Sort: O(n log n) GUARANTEED in all cases — predictable performance."),
p("For a university asset system: predictability matters. One slow sort during a demo = fail."),
h("Where Merge Sort is Used in Our Project"),
p("Sort dropdown in Asset Manager has two new options added after base implementation:"),
p("  'Value (Merge Sort - D&C)' → calls m_dsa.mergeSortByValue(records)"),
p("  'Name (Merge Sort - D&C)'  → calls m_dsa.mergeSortByName(records)"),
p("In sortAssets() in assetwindow.cpp — same call site as Bubble/Selection Sort."),
p("Demo tip: sort by value using Bubble Sort, then same data with Merge Sort."),
p2("Both give identical sorted results but Merge Sort is O(n log n) vs O(n²)."),
])

# ── SLIDE 27: MERGE SORT CODE ─────────────────────────────────
sl = slide()
title(sl,"Merge Sort — Complete Code (Divide and Conquer)")
body(sl,[
h("Entry Point — mergeSortByValue()"),
code("void DSAEngine::mergeSortByValue(std::vector<AssetRecord> &assets) {"),
code("    if (assets.size() > 1)"),
code("        mergeSortHelperByValue(assets, 0, (int)assets.size()-1);"),
code("}"),
h("DIVIDE step — mergeSortHelperByValue() — Recursive"),
code("void DSAEngine::mergeSortHelperByValue("),
code("        std::vector<AssetRecord> &a, int l, int r) {"),
code("    if (l >= r) return;              // BASE CASE: single element"),
code("    int m = l + (r - l) / 2;        // find midpoint (avoids overflow)"),
code("    mergeSortHelperByValue(a, l, m);     // DIVIDE: sort left half"),
code("    mergeSortHelperByValue(a, m+1, r);   // DIVIDE: sort right half"),
code("    mergeByValue(a, l, m, r);           // CONQUER: merge sorted halves"),
code("}"),
h("CONQUER step — mergeByValue() — The actual merge"),
code("void DSAEngine::mergeByValue("),
code("        std::vector<AssetRecord> &a, int l, int m, int r) {"),
code("    // Copy both halves into temporary vectors"),
code("    std::vector<AssetRecord> left (a.begin()+l,   a.begin()+m+1);"),
code("    std::vector<AssetRecord> right(a.begin()+m+1, a.begin()+r+1);"),
code("    int i=0, j=0, k=l;"),
code("    // Merge: pick smaller element from left or right"),
code("    while (i<(int)left.size() && j<(int)right.size())"),
code("        a[k++] = (left[i].value <= right[j].value) ? left[i++] : right[j++];"),
code("    // Copy remaining elements"),
code("    while (i<(int)left.size())  a[k++]=left[i++];"),
code("    while (j<(int)right.size()) a[k++]=right[j++];"),
code("}"),
h("Complexity Proof via Recurrence"),
p("T(n) = 2·T(n/2) + O(n)"),
p("  2·T(n/2): two recursive calls each on half the data"),
p("  O(n): the merge step scans all elements"),
p("By Master Theorem (Case 2): a=2, b=2, f(n)=n, log_b(a)=log_2(2)=1"),
p("f(n) = Θ(n^log_b(a)) = Θ(n¹) = Θ(n)  →  T(n) = Θ(n log n)"),
p("Space: merge creates two temp vectors totalling n elements → O(n) auxiliary"),
])

# ── SLIDE 28: CH9 DIVIDER ─────────────────────────────────────
sl = slide()
title(sl,"Chapter 9 — Algorithmic Strategies")
body(sl,[
h("Chapter Overview"),
p("Chapter 9 introduces high-level problem-solving strategies (paradigms) that guide"),
p2("the design of efficient algorithms. These are meta-strategies, not individual algorithms."),
h("Strategies Covered in the Course"),
p("Brute Force:        Try every possible solution. O(n²) or worse. Simple to implement."),
p("Divide & Conquer:   Divide into subproblems, solve recursively, combine. O(n log n)."),
p("Greedy:             Make locally optimal choice at each step. O(n log n) for sort."),
p("Backtracking:       Try all paths, undo when stuck. Used in DFS connectivity."),
p("Branch & Bound:     Pruned exhaustive search. Not directly implemented."),
p("Dynamic Programming: Store results of subproblems (memoization). Not directly in scope."),
p("Pattern Matching:   KMP, Rabin-Karp. Our SQL LIKE is a simple form of this."),
h("Strategies Implemented in Our Project"),
p("Divide & Conquer → Merge Sort: splits array in half recursively, merges back"),
p2("  Code: mergeSortHelperByValue() in dsaengine.cpp"),
p2("  The classic example — directly from Ch.8 and Ch.9 simultaneously"),
p("Greedy → Maintenance Priority Scheduler"),
p2("  Strategy: always service the task with highest urgency score first"),
p2("  Proof of optimality: greedy choice property holds for job scheduling"),
p2("  Code: greedyPrioritize() in maintenancewindow.cpp"),
h("Why Greedy Works for Our Scheduler"),
p("Greedy works when: (1) greedy choice property + (2) optimal substructure both hold."),
p("Greedy choice: picking URGENT first reduces maximum wait time globally."),
p("Optimal substructure: optimal schedule for remaining tasks after removing first"),
p2("task is independent of which first task we chose (they don't interfere)."),
p("This is identical to the 'weighted job scheduling by deadline' greedy problem."),
h("Brute Force in Our Project (for comparison)"),
p("The original loadData() in maintenancewindow.cpp loads tasks in DB insertion order."),
p("This is brute force — no optimization. Auto-Prioritize replaces it with greedy."),
])

# ── SLIDE 29: GREEDY CODE ─────────────────────────────────────
sl = slide()
title(sl,"Greedy Scheduling — Complete Code")
body(sl,[
h("greedyPrioritize() — maintenancewindow.cpp"),
code("void MaintenanceWindow::greedyPrioritize() {"),
code("    struct Row {"),
code("        int score;  QStringList cols;  QVector<QColor> fgColors;"),
code("    };"),
code("    QVector<Row> rows;"),
code("    for (int r = 0; r < table->rowCount(); r++) {"),
code("        Row row; row.score = 0;"),
code("        for (int c = 0; c < table->columnCount(); c++) {"),
code("            auto *it = table->item(r,c);"),
code("            row.cols     << (it ? it->text() : '');"),
code("            row.fgColors << (it ? it->foreground().color() : QColor('#cdd6f4'));"),
code("        }"),
code("        // GREEDY KEY: compute urgency score"),
code("        const QString &pri = row.cols[4];"),
code("        if      (pri=='URGENT') row.score += 40;"),
code("        else if (pri=='HIGH')   row.score += 30;"),
code("        else if (pri=='NORMAL') row.score += 20;"),
code("        else                    row.score += 10;  // LOW"),
code("        // Status modifier: unresolved tasks rank higher"),
code("        const QString &st = row.cols[5];"),
code("        if      (st=='PENDING')     row.score += 20;"),
code("        else if (st=='IN_PROGRESS') row.score += 10;"),
code("        rows.append(row);"),
code("    }"),
code("    // GREEDY SELECTION: sort by score descending — O(n log n)"),
code("    std::sort(rows.begin(), rows.end(),"),
code("              [](const Row &a, const Row &b){ return a.score > b.score; });"),
code("    // Repopulate table in prioritized order"),
code("    table->setRowCount(0);"),
code("    for (const Row &row : rows) {  /* re-insert each row */ }"),
code("    greedyLabel->setText(QString('Greedy: %1 tasks ranked...').arg(rows.size()));"),
code("}"),
h("Score Table — How Greedy Ranks Tasks"),
p("URGENT + PENDING     = 40+20 = 60  → highest priority  (fix immediately)"),
p("URGENT + IN_PROGRESS = 40+10 = 50  → already being handled"),
p("HIGH + PENDING       = 30+20 = 50  → next in queue"),
p("HIGH + IN_PROGRESS   = 30+10 = 40"),
p("NORMAL + PENDING     = 20+20 = 40"),
p("NORMAL + IN_PROGRESS = 20+10 = 30"),
p("LOW + PENDING        = 10+20 = 30"),
p("LOW + IN_PROGRESS    = 10+10 = 20"),
p("RESOLVED (any)       = priority + 0 = ≤40  → lowest (already done)"),
])

# ── SLIDE 30: ORACLE CONNECTION ──────────────────────────────
sl = slide()
title(sl,"Oracle XE — Connection Details and Startup")
body(sl,[
h("Connection Configuration — widget.cpp"),
code("QSqlDatabase db = QSqlDatabase::addDatabase('QODBC');"),
code("db.setDatabaseName("),
code("    'Driver={Oracle in XE};'"),
code("    'DBQ=127.0.0.1:1522/xe;'"),
code(");"),
code("db.setUserName('campus_admin');"),
code("db.setPassword('campus123');"),
code("if (!db.open()) {"),
code("    QMessageBox::critical(this, 'DB Error', db.lastError().text());"),
code("    return;"),
code("}"),
h("Connect via Command Line (SQL*Plus)"),
code("sqlplus campus_admin/campus123@//127.0.0.1:1522/xe"),
p("After connecting, run this to verify:"),
code("SELECT 'Connected as: ' || USER || ' on ' || TO_CHAR(SYSDATE,'DD-MON-YYYY') FROM DUAL;"),
h("Start Oracle Services on Windows (run as Administrator)"),
code("net start OracleServiceXE"),
code("net start OracleXETNSListener"),
p("Check if already running:"),
code("sc query OracleServiceXE"),
code("sc query OracleXETNSListener"),
p("If port 1522 is occupied by another process:"),
code("netstat -ano | findstr :1522"),
p("Find the PID from above and kill it:"),
code("taskkill /PID <pid> /F"),
h("Verify All Tables Exist"),
code("SELECT TABLE_NAME FROM USER_TABLES ORDER BY TABLE_NAME;"),
p("Expected: ASSETS, LOCATIONS, LOST_FOUND, MAINTENANCE_LOG, STUDENT_ITEMS, USERS"),
h("Check ODBC Driver Installed"),
p("Windows: Control Panel → Administrative Tools → ODBC Data Sources (64-bit)"),
p("Must see 'Oracle in XE' in the Drivers tab"),
p("If missing: install Oracle Instant Client + ODBC driver package"),
])

# ── SLIDE 31: ORACLE RESET ────────────────────────────────────
sl = slide()
title(sl,"Oracle — Reset Commands (Clean State for Demo)")
body(sl,[
h("Step 1: Disable Foreign Key Constraints"),
code("ALTER TABLE MAINTENANCE_LOG DISABLE CONSTRAINT FK_MAINT_ASSET;"),
code("ALTER TABLE MAINTENANCE_LOG DISABLE CONSTRAINT FK_MAINT_USER;"),
code("ALTER TABLE STUDENT_ITEMS   DISABLE CONSTRAINT FK_ITEMS_USER;"),
code("ALTER TABLE LOST_FOUND      DISABLE CONSTRAINT FK_LF_USER;"),
code("ALTER TABLE ASSETS          DISABLE CONSTRAINT FK_ASSET_LOCATION;"),
code("ALTER TABLE ASSETS          DISABLE CONSTRAINT FK_ASSET_CREATED_BY;"),
p("Note: constraint names may differ. Find yours with:"),
code("SELECT CONSTRAINT_NAME, TABLE_NAME FROM USER_CONSTRAINTS WHERE TABLE_NAME='MAINTENANCE_LOG';"),
h("Step 2: Delete All Rows (child tables first)"),
code("DELETE FROM MAINTENANCE_LOG;"),
code("DELETE FROM LOST_FOUND;"),
code("DELETE FROM STUDENT_ITEMS;"),
code("DELETE FROM ASSETS;"),
code("DELETE FROM LOCATIONS;"),
code("DELETE FROM USERS WHERE ROLE != 'ADMIN';  -- keep at least one admin"),
h("Step 3: Reset Auto-Increment Sequences to 1"),
code("DROP SEQUENCE SEQ_ASSETS;"),
code("CREATE SEQUENCE SEQ_ASSETS START WITH 1 INCREMENT BY 1 NOCACHE;"),
code("DROP SEQUENCE SEQ_MAINTENANCE;"),
code("CREATE SEQUENCE SEQ_MAINTENANCE START WITH 1 INCREMENT BY 1 NOCACHE;"),
code("DROP SEQUENCE SEQ_STUDENT_ITEMS;"),
code("CREATE SEQUENCE SEQ_STUDENT_ITEMS START WITH 1 INCREMENT BY 1 NOCACHE;"),
code("DROP SEQUENCE SEQ_LOST_FOUND;"),
code("CREATE SEQUENCE SEQ_LOST_FOUND START WITH 1 INCREMENT BY 1 NOCACHE;"),
h("Step 4: Re-Enable Constraints and Commit"),
code("ALTER TABLE MAINTENANCE_LOG ENABLE CONSTRAINT FK_MAINT_ASSET;"),
code("ALTER TABLE MAINTENANCE_LOG ENABLE CONSTRAINT FK_MAINT_USER;"),
code("ALTER TABLE STUDENT_ITEMS   ENABLE CONSTRAINT FK_ITEMS_USER;"),
code("ALTER TABLE LOST_FOUND      ENABLE CONSTRAINT FK_LF_USER;"),
code("COMMIT;"),
h("Step 5: Verify Clean State"),
code("SELECT COUNT(*) FROM ASSETS;         -- should be 0"),
code("SELECT COUNT(*) FROM MAINTENANCE_LOG; -- should be 0"),
code("SELECT COUNT(*) FROM STUDENT_ITEMS;  -- should be 0"),
code("SELECT SEQUENCE_NAME, LAST_NUMBER FROM USER_SEQUENCES;"),
])

# ── SLIDE 32: INSERT TEST DATA ────────────────────────────────
sl = slide()
title(sl,"Oracle — Insert Test Data for Full Demo")
body(sl,[
h("Insert Locations"),
code("INSERT INTO LOCATIONS VALUES(1,'College of Computing','CL03','Ground');"),
code("INSERT INTO LOCATIONS VALUES(2,'Admin Block','DA03','Floor 2');"),
code("INSERT INTO LOCATIONS VALUES(3,'Lab Block','LAB01','Ground');"),
code("COMMIT;"),
h("Insert Users (all roles)"),
code("INSERT INTO USERS VALUES(1,'Admin User','ADM001','admin@dbu.edu.et','ADMIN','admin123');"),
code("INSERT INTO USERS VALUES(2,'Bereket Tadesse','DBU/1234/15','b@dbu.et','STUDENT','pass123');"),
code("INSERT INTO USERS VALUES(3,'Security Guard','SEC001','sec@dbu.et','SECURITY','sec123');"),
code("INSERT INTO USERS VALUES(4,'Tech Abebe','TEC001','tech@dbu.et','TECHNICIAN','tech123');"),
code("COMMIT;"),
h("Insert Assets"),
code("INSERT INTO ASSETS(ASSET_ID,ASSET_NAME,CATEGORY,SERIAL_NUMBER,PURCHASE_VALUE,CONDITION,LOCATION_ID,CREATED_BY)"),
code("VALUES(SEQ_ASSETS.NEXTVAL,'Dell Laptop 15','IT_EQUIPMENT','DL-2024-001',45000,'GOOD',1,1);"),
code("INSERT INTO ASSETS(ASSET_ID,ASSET_NAME,CATEGORY,SERIAL_NUMBER,PURCHASE_VALUE,CONDITION,LOCATION_ID,CREATED_BY)"),
code("VALUES(SEQ_ASSETS.NEXTVAL,'Epson Projector','IT_EQUIPMENT','EP-2023-042',28000,'GOOD',1,1);"),
code("INSERT INTO ASSETS(ASSET_ID,ASSET_NAME,CATEGORY,SERIAL_NUMBER,PURCHASE_VALUE,CONDITION,LOCATION_ID,CREATED_BY)"),
code("VALUES(SEQ_ASSETS.NEXTVAL,'Lab Microscope','LAB_EQUIPMENT','MIC-001',120000,'UNDER_MAINTENANCE',3,1);"),
code("INSERT INTO ASSETS(ASSET_ID,ASSET_NAME,CATEGORY,SERIAL_NUMBER,PURCHASE_VALUE,CONDITION,LOCATION_ID,CREATED_BY)"),
code("VALUES(SEQ_ASSETS.NEXTVAL,'Office Chair','FURNITURE','CHR-2024-010',3500,'GOOD',2,1);"),
code("COMMIT;"),
h("Insert Student Items (critical for BST + Security demo)"),
code("INSERT INTO STUDENT_ITEMS(ITEM_ID,STUDENT_ID,ITEM_NAME,CATEGORY,BRAND,SERIAL_NUMBER,STATUS)"),
code("VALUES(1,2,'MacBook Pro 14','LAPTOP','Apple','MB-PRO-2024-XYZ','REGISTERED');"),
code("INSERT INTO STUDENT_ITEMS(ITEM_ID,STUDENT_ID,ITEM_NAME,CATEGORY,BRAND,SERIAL_NUMBER,STATUS)"),
code("VALUES(2,2,'Samsung Galaxy S23','PHONE','Samsung','SM-G998B-123','REGISTERED');"),
code("INSERT INTO STUDENT_ITEMS(ITEM_ID,STUDENT_ID,ITEM_NAME,CATEGORY,BRAND,SERIAL_NUMBER,STATUS)"),
code("VALUES(3,2,'Sony WH-1000XM5','HEADPHONES','Sony','WH1000XM5-DBU','REGISTERED');"),
code("COMMIT;"),
h("Insert Maintenance Log (for Greedy demo — mix of priorities)"),
code("BEGIN SP_REPORT_ISSUE(1,1,'BROKEN','Screen cracked badly, cannot work','URGENT'); END;"),
code("BEGIN SP_REPORT_ISSUE(2,4,'MISSING','Power cable missing','NORMAL'); END;"),
code("BEGIN SP_REPORT_ISSUE(3,4,'SCHEDULED','Annual calibration due','LOW'); END;"),
code("BEGIN SP_REPORT_ISSUE(1,1,'SCHEDULED','Maintenance overdue 3 months','HIGH'); END;"),
code("COMMIT;"),
])

# ── SLIDE 33: TEST STORED PROCS ───────────────────────────────
sl = slide()
title(sl,"Oracle — Test Stored Procedures")
body(sl,[
h("Test SP_REPORT_ISSUE"),
code("-- Call the procedure"),
code("BEGIN"),
code("    SP_REPORT_ISSUE("),
code("        :asset_id    => 1,"),
code("        :reported_by => 1,"),
code("        :issue_type  => 'BROKEN',"),
code("        :description => 'Keyboard not responding',"),
code("        :priority    => 'HIGH'"),
code("    );"),
code("END;"),
code("/"),
code("-- Verify: should see new row with STATUS='PENDING'"),
code("SELECT MAINTENANCE_ID, ASSET_ID, PRIORITY, STATUS, REPORTED_AT"),
code("FROM   MAINTENANCE_LOG"),
code("ORDER  BY REPORTED_AT DESC"),
code("FETCH FIRST 3 ROWS ONLY;"),
h("Test SP_RESOLVE_MAINTENANCE"),
code("BEGIN"),
code("    SP_RESOLVE_MAINTENANCE("),
code("        :maintenance_id  => 1,"),
code("        :resolved_by     => 1,"),
code("        :resolution_note => 'Keyboard replaced with spare unit'"),
code("    );"),
code("END;"),
code("/"),
code("-- Verify: STATUS should now be RESOLVED, RESOLVED_AT should be populated"),
code("SELECT STATUS, RESOLVED_AT, RESOLUTION_NOTE"),
code("FROM   MAINTENANCE_LOG"),
code("WHERE  MAINTENANCE_ID = 1;"),
h("Test Security Check Flow via SQL"),
code("-- Simulate student leaving campus"),
code("UPDATE STUDENT_ITEMS SET STATUS='OUT_OF_CAMPUS' WHERE ITEM_ID=1;"),
code("COMMIT;"),
code("-- Now search 'MB-PRO-2024-XYZ' in Security Check → should show orange warning"),
code(""),
code("-- Simulate student returning"),
code("UPDATE STUDENT_ITEMS SET STATUS='REGISTERED' WHERE ITEM_ID=1;"),
code("COMMIT;"),
code("-- Search again → should show green 'Allow Exit'"),
h("Verify Oracle Sequences are Incrementing"),
code("-- Get next asset ID (should increment each time)"),
code("SELECT SEQ_ASSETS.NEXTVAL FROM DUAL;"),
code("SELECT SEQ_ASSETS.CURRVAL FROM DUAL;"),
code("-- Reset sequence: drop and recreate (see reset slide)"),
])

# ── SLIDE 34: VERIFY QUERIES ──────────────────────────────────
sl = slide()
title(sl,"Oracle — Verification Queries Before Demo")
body(sl,[
h("Run All of These Before Opening the App for Demo"),
code("-- 1. Row counts in all tables"),
code("SELECT 'ASSETS'          AS tbl, COUNT(*) AS cnt FROM ASSETS"),
code("UNION ALL SELECT 'USERS',          COUNT(*) FROM USERS"),
code("UNION ALL SELECT 'STUDENT_ITEMS',  COUNT(*) FROM STUDENT_ITEMS"),
code("UNION ALL SELECT 'MAINTENANCE_LOG',COUNT(*) FROM MAINTENANCE_LOG"),
code("UNION ALL SELECT 'LOST_FOUND',     COUNT(*) FROM LOST_FOUND"),
code("UNION ALL SELECT 'LOCATIONS',      COUNT(*) FROM LOCATIONS;"),
code(""),
code("-- 2. Asset condition distribution"),
code("SELECT CONDITION, COUNT(*) AS total"),
code("FROM   ASSETS"),
code("GROUP  BY CONDITION ORDER BY total DESC;"),
code(""),
code("-- 3. Maintenance priority/status mix (important for Greedy demo)"),
code("SELECT PRIORITY, STATUS, COUNT(*) AS total"),
code("FROM   MAINTENANCE_LOG"),
code("GROUP  BY PRIORITY, STATUS"),
code("ORDER  BY PRIORITY, STATUS;"),
code("-- Should have at least: one URGENT+PENDING, one HIGH, one NORMAL, one LOW"),
code(""),
code("-- 4. Student items and their current status"),
code("SELECT si.ITEM_ID, si.ITEM_NAME, si.SERIAL_NUMBER, si.STATUS,"),
code("       u.FULL_NAME AS owner"),
code("FROM   STUDENT_ITEMS si"),
code("JOIN   USERS u ON si.STUDENT_ID = u.USER_ID;"),
code("-- All should be REGISTERED before demo (none OUT_OF_CAMPUS)"),
code(""),
code("-- 5. Check all user roles exist"),
code("SELECT ROLE, COUNT(*) FROM USERS GROUP BY ROLE ORDER BY ROLE;"),
code("-- Should see ADMIN, STUDENT, SECURITY, TECHNICIAN"),
code(""),
code("-- 6. Confirm sequences active"),
code("SELECT SEQUENCE_NAME, MIN_VALUE, MAX_VALUE, INCREMENT_BY, LAST_NUMBER"),
code("FROM   USER_SEQUENCES;"),
h("Quick Sanity Check"),
code("SELECT 'DB Ready for Demo' AS status FROM DUAL"),
code("WHERE (SELECT COUNT(*) FROM ASSETS) >= 3"),
code("  AND (SELECT COUNT(*) FROM MAINTENANCE_LOG) >= 2"),
code("  AND (SELECT COUNT(*) FROM STUDENT_ITEMS) >= 2;"),
p("If this query returns a row: database is ready."),
p("If no row returned: re-run the insert test data commands first."),
])

# ── SLIDE 35: SECURITY CHECK TESTING ─────────────────────────
sl = slide()
title(sl,"Security Check Window — Complete Testing Guide")
body(sl,[
h("How the Security Check Window Works"),
p("1. Window opens → loadSerialsBST() is called automatically"),
p2("   Queries: SELECT ITEM_ID, SERIAL_NUMBER FROM STUDENT_ITEMS WHERE SERIAL_NUMBER IS NOT NULL"),
p2("   Each serial is inserted into the BST: m_dsa.bstInsert(serial, itemId)"),
p2("   Blue info bar shows: 'BST Index: N serials loaded | Height: H | O(log n) ≈ X comparisons'"),
p("2. User types a serial number and clicks Search (or presses Enter)"),
p2("   Step 1: m_dsa.bstSearch() runs — O(log n) — result shown in blue bar"),
p2("   Step 2: Oracle SQL query runs — full record details fetched"),
p2("   Step 3: Table populated, action buttons enabled based on item status"),
h("Test Case 1 — Registered Item (normal exit)"),
p("Precondition: STUDENT_ITEMS has ITEM_ID=1 with STATUS='REGISTERED'"),
p("Action: type 'MB-PRO-2024-XYZ' in the serial field, click Search"),
p("Expected: green message 'Registered item found. Allow exit after ID check.'"),
p2("          'Allow Exit' button becomes enabled. 'Deny Exit' button enabled."),
p2("          Blue bar: 'BST: FOUND in O(log n) ≈ X comparisons'"),
h("Test Case 2 — Item Already Out of Campus"),
p("Precondition: run SQL → UPDATE STUDENT_ITEMS SET STATUS='OUT_OF_CAMPUS' WHERE ITEM_ID=1; COMMIT;"),
p("Action: search 'MB-PRO-2024-XYZ' again"),
p("Expected: orange message 'Item is currently OUT OF CAMPUS. Click Mark Returned.'"),
p2("          'Mark Returned' button enabled. 'Allow Exit' disabled."),
h("Test Case 3 — Unknown Serial (unregistered item)"),
p("Action: type 'FAKE-SERIAL-99999' in the field, click Search"),
p("Expected: red message 'No registered item found. Deny exit until verified.'"),
p2("          Blue bar: 'BST: FAKE-SERIAL-99999 NOT in index'"),
p2("          Only 'Deny Exit' button enabled."),
h("Test Case 4 — Mark Returned"),
p("Precondition: item status is 'OUT_OF_CAMPUS'"),
p("Action: search the serial → click 'Mark Returned'"),
p("Expected: Oracle UPDATE runs: SET STATUS='REGISTERED' WHERE ITEM_ID=:id"),
p2("          Confirmation dialog 'Asset marked as returned to campus.'"),
p2("          Search refreshes automatically → status now shows REGISTERED"),
h("Test Case 5 — Role Access"),
p("Login as STUDENT role: Security Check button must NOT appear in sidebar"),
p("Login as TECHNICIAN role: Security Check button must NOT appear"),
p("Login as SECURITY or ADMIN: Security Check button appears"),
p("Code: widget.cpp → btnSecurity->setVisible(role=='SECURITY' || role=='ADMIN')"),
])

# ── SLIDE 36: ROLE ACCESS TESTING ────────────────────────────
sl = slide()
title(sl,"Role-Based Access Testing — applyRoleAccess()")
body(sl,[
h("SQL — Create Test Accounts for Each Role"),
code("INSERT INTO USERS VALUES(10,'Test Admin',   'A01','a@dbu.et','ADMIN',     'pass');"),
code("INSERT INTO USERS VALUES(11,'Test Tech',    'T01','t@dbu.et','TECHNICIAN','pass');"),
code("INSERT INTO USERS VALUES(12,'Test Security','S01','s@dbu.et','SECURITY',  'pass');"),
code("INSERT INTO USERS VALUES(13,'Test Auditor', 'AU1','u@dbu.et','AUDITOR',   'pass');"),
code("INSERT INTO USERS VALUES(14,'Test Student', 'ST1','st@dbu.et','STUDENT',  'pass');"),
code("COMMIT;"),
h("Expected Sidebar Visibility Per Role"),
p("ADMIN:      Home ✓  Assets ✓  Maintenance ✓  LostFound ✓  MyItems ✓  Users ✓  Security ✓  Graph ✓"),
p("TECHNICIAN: Home ✓  Assets ✓  Maintenance ✓  LostFound ✓  MyItems ✓  Users ✗  Security ✗  Graph ✓"),
p("SECURITY:   Home ✓  Assets ✗  Maintenance ✗  LostFound ✓  MyItems ✓  Users ✗  Security ✓  Graph ✓"),
p("AUDITOR:    Home ✓  Assets ✓  Maintenance ✓  LostFound ✓  MyItems ✓  Users ✗  Security ✗  Graph ✓"),
p("STUDENT:    Home ✓  Assets ✗  Maintenance ✓  LostFound ✓  MyItems ✓  Users ✗  Security ✗  Graph ✓"),
h("RolePolicy Struct in widget.cpp"),
code("static RolePolicy forRole(const QString &role) {"),
code("    if (role=='ADMIN')      return {true, true, true, true, true, true, true, true, true};"),
code("    if (role=='TECHNICIAN') return {true,false,false, true, true, true, true, true,false};"),
code("    if (role=='AUDITOR')    return {true,false,false, true,false,false, true, true,false};"),
code("    if (role=='SECURITY')   return {false,false,false,false,false,false,true, true,false};"),
code("    // STUDENT default"),
code("    return {false,false,false,true,true,false,true,false,false};"),
code("}"),
h("Testing Access Denial"),
p("Try to navigate to Assets as SECURITY role (even if you know the URL/button):"),
p2("showAccessDenied() in widget.cpp displays '🔒 Access Denied — Your role (SECURITY)"),
p2("does not have permission to access: Assets'"),
p("This means you cannot bypass role checks by coding direct navigation."),
h("Maintenance Resolve Button Visibility"),
p("In maintenancewindow.cpp setupUI():"),
code("if (m_role=='STUDENT') resolveBtn->setVisible(false);"),
p("Students can REPORT issues but cannot RESOLVE them. Test by logging in as STUDENT"),
p2("and opening Maintenance — '✔ Resolve Issue' button should be hidden."),
])

# ── SLIDE 37: DEMO GUIDE ──────────────────────────────────────
sl = slide()
title(sl,"Live Demo Guide — Exact Click Sequence (10 minutes)")
body(sl,[
h("Preparation — Before Demo"),
p("1. Run Oracle verification queries (Slide 34) — confirm all counts correct"),
p("2. Close and reopen the app — ensures BST is freshly loaded"),
p("3. Have SQL*Plus or SQL Developer open in background for query demos"),
p("4. Have the code open in VS Code side-by-side if examiner asks for code"),
h("Demo Step 1 — Login and Dashboard (30 sec)"),
p("Action: launch app, login as ADMIN with campus_admin/admin123"),
p("Point out: 4 stat cards (Total Assets, Student Items, Maintenance, Lost&Found)"),
p("Say: 'Role-based access — only ADMIN sees all 8 sidebar buttons. Oracle queries populate the counts.'"),
h("Demo Step 2 — Stack Demo in Asset Manager (90 sec)"),
p("Action: click Assets in sidebar → add a new asset (any name, IT_EQUIPMENT)"),
p("Point out: 'Undo: 1 | Redo: 0' counter in top-right → pushUndo() was called"),
p("Action: add 2 more assets"),
p("Point out: 'Undo: 3 | Redo: 0'"),
p("Action: click Undo once"),
p("Point out: 'Undo: 2 | Redo: 1' → asset disappeared from table → Oracle DELETE ran"),
p("Say: 'Stack is LIFO — the last asset added is the first one undone. O(1) per operation.'"),
h("Demo Step 3 — Sort Comparison (60 sec)"),
p("Action: sort dropdown → 'ID (Bubble Sort)'"),
p("Say: 'Bubble Sort O(n²) — compares adjacent pairs, n²/2 comparisons total'"),
p("Action: sort dropdown → 'Value (Merge Sort - D&C)'"),
p("Say: 'Merge Sort O(n log n) — same result but 50× fewer operations for large data.'"),
p("Action: sort dropdown → 'Name (Selection Sort)'"),
p("Say: 'Selection Sort finds minimum each pass. O(n²) but fewer swaps than Bubble.'"),
h("Demo Step 4 — Greedy Scheduler (45 sec)"),
p("Action: click Maintenance in sidebar"),
p("Point out: tasks loaded in DB order (brute force — no prioritization)"),
p("Action: click '⚡ Auto-Prioritize' button"),
p("Point out: URGENT+PENDING moves to top. RESOLVED tasks drop to bottom."),
p("Say: 'Greedy algorithm — always schedules highest urgency task first. O(n log n) sort.'"),
h("Demo Step 5 — BST in Security Check (60 sec)"),
p("Action: click 'Security Check' in sidebar"),
p("Point out: blue bar shows 'BST Index: N serials loaded | Height: H'"),
p("Say: 'When this window opened, all serial numbers were inserted into our custom BST.'"),
p("Action: type 'MB-PRO-2024-XYZ' → click Search"),
p("Point out: BST bar updates: 'FOUND in O(log n) ≈ X comparisons vs O(n)=N linear'"),
p("Say: 'BST found it in X comparisons. A linear scan would need N comparisons.'"),
h("Demo Step 6 — Campus Graph BFS/DFS (90 sec)"),
p("Action: click 'Campus Graph' in sidebar"),
p("Point out: adjacency list on the left — all 10 buildings and their connections"),
p("Action: Set From='Main Gate', To='Medical Center', click '▶ Run BFS'"),
p("Point out: path shown with hop count and step-by-step BFS explanation"),
p("Say: 'BFS uses a queue to explore level by level. Guarantees shortest path. O(V+E).'"),
p("Action: set Start='College of Computing', click '▶ Run DFS'"),
p("Point out: all 10 buildings listed in DFS visit order"),
p("Say: 'DFS uses recursion (call stack). Visits as deep as possible before backtracking.'"),
])

# ── SLIDE 38: EXAM Q&A ────────────────────────────────────────
sl = slide()
title(sl,"Expected Exam Questions and Model Answers")
body(sl,[
h("Q1: Why did you use a custom linked list instead of std::queue?"),
p("Answer: std::queue internally uses std::deque which allocates memory in fixed-size blocks."),
p("Our custom LLNode allocates exactly one node per action — no wasted capacity."),
p("More importantly, implementing a custom linked list directly demonstrates Chapter 3"),
p2("material (LLNode struct, head/tail pointers, dynamic memory with new/delete)."),
p("Using std::queue would hide the data structure implementation from the examiner."),
h("Q2: Your BST worst case is O(n). When does this happen?"),
p("Answer: When all serial numbers are inserted in alphabetical order (e.g., SN-001, SN-002, SN-003...)."),
p("Each new node becomes the right child of the previous one — the tree degenerates into a list."),
p("Height becomes n (not log n), so search is O(n) not O(log n)."),
p("In practice, serial numbers like 'MB-PRO-2024-XYZ', 'SM-G998B-123' are not sorted"),
p2("— they're random strings. The BST stays approximately balanced: O(log n) in practice."),
p("To guarantee O(log n): use a self-balancing tree (AVL or Red-Black) — outside course scope."),
h("Q3: Why did you choose Merge Sort instead of Quick Sort?"),
p("Answer: Merge Sort guarantees O(n log n) in ALL cases (best, average, worst)."),
p("Quick Sort is O(n log n) average but degrades to O(n²) with bad pivot choice"),
p2("(e.g., always picking first element as pivot on already-sorted data)."),
p("For a production asset management system, predictable performance is critical."),
p("One O(n²) sort during a demo on sorted data would be embarrassing."),
h("Q4: How does the Greedy algorithm guarantee the optimal schedule?"),
p("Answer: Two conditions for greedy correctness: (1) Greedy Choice Property and (2) Optimal Substructure."),
p("Greedy Choice: selecting the highest-urgency task first minimizes the maximum waiting time"),
p2("for critical tasks globally, not just locally."),
p("Optimal Substructure: the optimal schedule for the remaining tasks after removing"),
p2("the first task is independent of which task we selected first."),
p("This is equivalent to the 'Earliest Deadline First' scheduling algorithm, proven optimal."),
h("Q5: Why use BFS for shortest path and not DFS?"),
p("Answer: DFS explores as deep as possible first — it can find A PATH but not the SHORTEST path."),
p("Example: DFS from Main Gate to Lab Block might go Main Gate→Library→College of Computing→Lab Block (3 hops)"),
p2("instead of Main Gate→Admin Block→Lab Block (2 hops — the shortest)."),
p("BFS explores level by level using a queue. It always finds the minimum-hop path first."),
p("In an unweighted graph (all edges have equal cost), BFS shortest path = minimum hops."),
h("Q6: What happens if two assets have the same serial number in the BST?"),
p("Answer: The bstInsertHelper() function handles this with the 'else if (serial > node->serial)' check."),
p("If the serial exactly equals the current node's serial (neither < nor >), the function"),
p2("falls through to 'return node' — the duplicate is silently ignored."),
p("In practice: the Oracle DB has a UNIQUE constraint on SERIAL_NUMBER column, so"),
p2("two items cannot have the same serial in the DB. The BST duplicate handling is a safety net."),
])

# ── SLIDE 39: DSA COVERAGE SUMMARY ───────────────────────────
sl = slide()
title(sl,"Complete DSA Coverage — All 9 Chapters Implemented")
body(sl,[
h("Chapter 1 — Complexity Analysis  [CLO2]"),
p("Implementation: Big-O comment headers on every function in dsaengine.cpp"),
p("Files: dsaengine.cpp (all functions), presented in Complexity Table slide"),
h("Chapter 2 — Simple Sorting and Searching  [CLO3]"),
p("Implementation: bubbleSortById, bubbleSortByValue, selectionSortByName, selectionSortByLocation"),
p("Files: dsaengine.h, dsaengine.cpp, assetwindow.cpp (sortAssets method)"),
h("Chapter 3 — Linked Lists  [CLO1, CLO4]"),
p("Implementation: Custom singly-linked list (LLNode struct) as action log"),
p("Files: dsaengine.h (LLNode struct), dsaengine.cpp (llEnqueue, llDequeue, llContents)"),
h("Chapter 4 — Stacks and Queues  [CLO1, CLO4]"),
p("Implementation: std::stack<AssetSnapshot> for undo/redo, linked list as queue"),
p("Files: dsaengine.h (pushUndo/popUndo), assetwindow.cpp (undoAction, redoAction)"),
h("Chapter 5 — Recursion  [CLO4, CLO5]"),
p("Implementation: 5 recursive functions: bstInsertHelper, bstSearchHelper, bstClearHelper, bstHeightHelper, graphDFS"),
p("Files: dsaengine.cpp (all 5 functions demonstrate different recursion types)"),
h("Chapter 6 — Trees / BST  [CLO1, CLO4]"),
p("Implementation: BST indexing all STUDENT_ITEMS serial numbers for O(log n) lookup"),
p("Files: dsaengine.h (BSTNode struct), dsaengine.cpp (bstInsert/Search/Clear/Height/Inorder)"),
p("Integration: securitycheckwindow.cpp (loadSerialsBST, searchItem)"),
h("Chapter 7 — Graphs  [CLO1, CLO4]"),
p("Implementation: DBU campus adjacency list graph, BFS shortest path, DFS traversal"),
p("Files: dsaengine.cpp (graphInit, graphBFS, graphDFS), campusgraphwindow.cpp (full UI)"),
h("Chapter 8 — Advanced Sorting  [CLO3]"),
p("Implementation: Merge Sort O(n log n) — both by value and by name"),
p("Files: dsaengine.cpp (mergeSortByValue, mergeSortByName, merge helpers)"),
h("Chapter 9 — Algorithmic Strategies  [CLO5]"),
p("Implementation: Greedy scheduling (maintenance priority), Divide & Conquer (Merge Sort)"),
p("Files: maintenancewindow.cpp (greedyPrioritize), dsaengine.cpp (mergeSortHelperByValue)"),
])

# ── SLIDE 40: GRADE ESTIMATE ──────────────────────────────────
sl = slide()
title(sl,"Grade Estimate — Project Assessment (20% of total grade)")
body(sl,[
h("Assessment Criteria from Course Outline — Week 14 Submission"),
p("Assessment: Course Project (team: code + demo + report) — 20% weight"),
p("CLOs assessed: 2, 3, 4, 5, 6, 7"),
h("CLO-by-CLO Score Estimate"),
p("CLO2 — Analyze complexity using asymptotic notation"),
p2("Evidence: Big-O comment headers on every function, complexity table in report"),
p2("Estimate: 20/20 — fully documented"),
p("CLO3 — Implement sorting and searching, evaluate performance"),
p2("Evidence: 6 sort algorithms (bubble×2, selection×2, merge×2) + linear + BST search"),
p2("Estimate: 19/20 — missing formal timing benchmark (would push to 20/20)"),
p("CLO4 — Apply appropriate data structures to optimize solutions"),
p2("Evidence: Stack for undo (LIFO), LL for queue (FIFO), BST for serial lookup, Graph for campus"),
p2("Each choice is justified: Stack because LIFO matches undo semantics, BST because O(log n) beats O(n)"),
p2("Estimate: 19/20 — excellent justifications"),
p("CLO5 — Design algorithms using greedy, divide & conquer, DP strategies"),
p2("Evidence: Greedy maintenance scheduler + Merge Sort (D&C) both implemented and working"),
p2("Dynamic Programming not implemented (not directly required for this application domain)"),
p2("Estimate: 17/20 — two of three strategies covered"),
p("CLO6 — Develop strong foundation in DS&A applicable in software development"),
p2("Evidence: All 9 chapters covered, real-world Qt/Oracle application, production-quality code"),
p2("Estimate: 20/20 — outstanding coverage"),
p("CLO7 — Collaborate in team to implement and analyze complex solution"),
p2("Evidence: Multi-module architecture (8 windows), role-based system, full CRUD with Oracle"),
p2("Estimate: 19/20 — comprehensive system"),
h("Project Score: 115/120 = 95.8% = A+"),
h("Overall Course Grade Depends On:"),
p("Mid-semester test (15% weight) — based on your individual written performance"),
p("Lab practical exams (15% weight) — based on your individual coding in lab"),
p("Final exam (50% weight) — most critical: must score at least 40% to pass"),
p("To secure A+ overall: need approximately 85%+ on final exam"),
])

# ── SLIDE 41: CONCLUSION ──────────────────────────────────────
sl = slide()
title(sl,"Conclusion — Smart Campus Asset Manager")
body(sl,[
h("What We Built"),
p("A complete role-based university asset management system for Debre Berhan University"),
p("serving 5 user roles (ADMIN, TECHNICIAN, SECURITY, AUDITOR, STUDENT) with:"),
p2("Full asset CRUD with undo/redo history (Stack)"),
p2("Real-time maintenance priority scheduling (Greedy)"),
p2("Campus exit/return verification with O(log n) serial lookup (BST)"),
p2("Interactive campus building path finder (Graph BFS/DFS)"),
p2("Efficient large-dataset sorting (Merge Sort O(n log n))"),
h("Technology Stack"),
p("Frontend: Qt 6 framework, C++17, custom dark theme UI"),
p("DSA Core: dsaengine.h/cpp — pure C++, zero Qt dependency, fully testable"),
p("Database: Oracle XE 21c, localhost:1522/xe, campus_admin schema"),
p("Driver: QODBC with Oracle In XE driver"),
h("DSA Concepts Demonstrated"),
p("Stack, Queue, Singly-Linked List, BST, Graph, Bubble Sort, Selection Sort,"),
p("Merge Sort (D&C), Greedy Scheduling, BFS, DFS, Recursion, Complexity Analysis"),
p("Covers all 9 chapters of SEng2022 and all 7 CLOs of the course."),
h("Key Technical Decisions and Justifications"),
p("Custom linked list over std::queue: demonstrates Ch.3 directly, same O(1) performance"),
p("BST over hash table: O(log n) search + sorted traversal for audit reports"),
p("Merge Sort over Quick Sort: O(n log n) guaranteed (no worst-case O(n²))"),
p("Greedy over brute force: provably optimal for urgency-based job scheduling"),
p("Recursive DFS to explicitly link Ch.5 (Recursion) with Ch.7 (Graph traversal)"),
h("Files Summary"),
p("dsaengine.h / dsaengine.cpp: ALL DSA logic (Stack, LL, BST, Graph, Sorts, Greedy)"),
p("assetwindow.cpp: Sort dropdown, Undo/Redo integration"),
p("securitycheckwindow.cpp: BST serial index, campus exit check"),
p("maintenancewindow.cpp: Greedy auto-prioritize button"),
p("campusgraphwindow.cpp: BFS/DFS interactive campus map"),
p("widget.cpp: Role-based routing, dashboard, sidebar navigation"),
h("Thank you — Questions are welcome"),
])

# ── SAVE ──────────────────────────────────────────────────────
out = r"c:\Users\berek\OneDrive\Documents\bereket\SmartCampus_DSA_Plain.pptx"
prs.save(out)
print(f"Saved: {out}")
print(f"Total slides: {len(prs.slides)}")
