from reportlab.lib.pagesizes import A4
from reportlab.lib import colors
from reportlab.lib.styles import ParagraphStyle
from reportlab.lib.units import cm
from reportlab.platypus import (SimpleDocTemplate, Paragraph, Spacer, Table,
                                 TableStyle, HRFlowable, KeepTogether)
from reportlab.lib.enums import TA_CENTER, TA_LEFT

DOC = "SmartCampus_DB_Full.pdf"

BLUE  = colors.HexColor("#003388")
BLACK = colors.black
GRAY  = colors.HexColor("#444444")
LGRAY = colors.HexColor("#cccccc")
WHITE = colors.white
LBG   = colors.HexColor("#f5f5f5")

def S(name, **kw):
    return ParagraphStyle(name, **kw)

sTitle  = S("T",  fontSize=20, textColor=BLUE,  fontName="Helvetica-Bold",
            alignment=TA_CENTER, spaceAfter=4)
sSub    = S("Su", fontSize=11, textColor=GRAY,  fontName="Helvetica",
            alignment=TA_CENTER, spaceAfter=4)
sH2     = S("H2", fontSize=13, textColor=BLUE,  fontName="Helvetica-Bold",
            spaceBefore=14, spaceAfter=4)
sH3     = S("H3", fontSize=10, textColor=BLACK, fontName="Helvetica-Bold",
            spaceBefore=8, spaceAfter=3)
sBody   = S("B",  fontSize=9,  textColor=BLACK, fontName="Helvetica", spaceAfter=3)
sCode   = S("C",  fontSize=8,  textColor=BLACK, fontName="Courier",   spaceAfter=2)
sNote   = S("N",  fontSize=8,  textColor=GRAY,  fontName="Helvetica-Oblique", spaceAfter=2)
sCenter = S("Cn", fontSize=9,  textColor=GRAY,  fontName="Helvetica", alignment=TA_CENTER)

doc = SimpleDocTemplate(DOC, pagesize=A4,
                        leftMargin=2*cm, rightMargin=2*cm,
                        topMargin=2*cm, bottomMargin=2*cm)
story = []

def hr():
    story.append(HRFlowable(width="100%", thickness=0.5, color=LGRAY, spaceAfter=6))

def sp(h=6):
    story.append(Spacer(1, h))

def heading(t):
    story.append(Paragraph(t, sH2))

def sub(t):
    story.append(Paragraph(t, sH3))

def body(t):
    story.append(Paragraph(t, sBody))

def code(t):
    story.append(Paragraph(t, sCode))

def note(t):
    story.append(Paragraph(t, sNote))

def plain_table(data, widths, header=True):
    style = [
        ("FONTSIZE",     (0,0),  (-1,-1), 8),
        ("FONTNAME",     (0,0),  (-1,-1), "Helvetica"),
        ("GRID",         (0,0),  (-1,-1), 0.4, LGRAY),
        ("ALIGN",        (0,0),  (-1,-1), "LEFT"),
        ("VALIGN",       (0,0),  (-1,-1), "MIDDLE"),
        ("TOPPADDING",   (0,0),  (-1,-1), 4),
        ("BOTTOMPADDING",(0,0),  (-1,-1), 4),
        ("LEFTPADDING",  (0,0),  (-1,-1), 6),
    ]
    if header:
        style += [
            ("BACKGROUND", (0,0), (-1,0), LBG),
            ("FONTNAME",   (0,0), (-1,0), "Helvetica-Bold"),
            ("TEXTCOLOR",  (0,0), (-1,0), BLUE),
        ]
    t = Table(data, colWidths=widths)
    t.setStyle(TableStyle(style))
    return t


# ── COVER ────────────────────────────────────────────────────
sp(1*cm)
story.append(Paragraph("SmartCampusManager", sTitle))
story.append(Paragraph("Database Relations, Schema &amp; Problem Solving Purpose", sSub))
story.append(Paragraph("Oracle XE  ·  campus_admin schema  ·  localhost:1522/xe", sCenter))
sp(4)
story.append(Paragraph("Course: SEng2022 — Design and Analysis of Data Structures and Algorithms", sCenter))
story.append(Paragraph("Debre Berhan University", sCenter))
hr()
sp(6)


# ════════════════════════════════════════════════════════
# 1. SCHEMA OVERVIEW
# ════════════════════════════════════════════════════════
heading("1. Schema Overview")
body("The database has 7 tables, 4 sequences, and 2 stored procedures. "
     "All primary keys are auto-generated by Oracle sequences.")
sp(4)

story.append(plain_table([
    ["Table",           "Purpose",                                         "PK Sequence"],
    ["USERS",           "All system users: Admin, Technician, Security, Auditor, Student", "SEQ_USERS"],
    ["ASSETS",          "University physical assets (equipment, furniture, etc.)",  "SEQ_ASSETS"],
    ["MAINTENANCE_LOG", "Repair/maintenance requests linked to assets",             "—"],
    ["STUDENT_ITEMS",   "Personal items registered by students",                   "SEQ_STUDENT_ITEMS"],
    ["LOST_FOUND",      "Lost or found item reports",                              "SEQ_LOST_FOUND"],
    ["LOCATIONS",       "Campus buildings and rooms",                              "—"],
    ["AUDIT_LOG",       "System-level event trail",                                "—"],
], [4.2*cm, 8.5*cm, 3.0*cm]))
sp(10)


# ════════════════════════════════════════════════════════
# 2. ENTITY-RELATIONSHIP SUMMARY
# ════════════════════════════════════════════════════════
heading("2. Entity-Relationship Summary")

story.append(plain_table([
    ["Parent Table", "Relation", "Child Table",      "Foreign Key Column"],
    ["USERS",        "1 — M",   "ASSETS",            "ASSETS.CREATED_BY"],
    ["USERS",        "1 — M",   "MAINTENANCE_LOG",   "MAINTENANCE_LOG.REPORTED_BY"],
    ["USERS",        "1 — M",   "STUDENT_ITEMS",     "STUDENT_ITEMS.STUDENT_ID"],
    ["USERS",        "1 — M",   "LOST_FOUND",        "LOST_FOUND.REPORTED_BY"],
    ["ASSETS",       "1 — M",   "MAINTENANCE_LOG",   "MAINTENANCE_LOG.ASSET_ID"],
    ["LOCATIONS",    "1 — M",   "STUDENT_ITEMS",     "STUDENT_ITEMS.LOCATION_ID"],
    ["LOCATIONS",    "1 — M",   "LOST_FOUND",        "LOST_FOUND.FOUND_LOCATION"],
], [3.5*cm, 2.0*cm, 4.0*cm, 6.2*cm]))
sp(10)


# ════════════════════════════════════════════════════════
# 3. TABLE DEFINITIONS
# ════════════════════════════════════════════════════════
heading("3. Table Definitions")

def tdef(name, pk_seq, rows, note_txt=None):
    hdr = [[f"TABLE: {name}    (PK sequence: {pk_seq})"]]
    hdr_style = TableStyle([
        ("BACKGROUND",   (0,0),(-1,-1), LBG),
        ("TEXTCOLOR",    (0,0),(-1,-1), BLUE),
        ("FONTNAME",     (0,0),(-1,-1), "Helvetica-Bold"),
        ("FONTSIZE",     (0,0),(-1,-1), 9),
        ("LEFTPADDING",  (0,0),(-1,-1), 8),
        ("TOPPADDING",   (0,0),(-1,-1), 4),
        ("BOTTOMPADDING",(0,0),(-1,-1), 4),
        ("BOX",          (0,0),(-1,-1), 0.5, LGRAY),
    ])
    ht = Table(hdr, colWidths=[15.7*cm])
    ht.setStyle(hdr_style)

    data = [["Column", "Type", "Constraint / Notes"]] + rows
    ct = plain_table(data, [4.0*cm, 3.2*cm, 8.5*cm])

    elems = [ht, ct]
    if note_txt:
        elems.append(Paragraph(f"Note: {note_txt}", sNote))
    elems.append(Spacer(1, 10))
    story.append(KeepTogether(elems))

tdef("USERS", "SEQ_USERS", [
    ["USER_ID",       "NUMBER",        "PRIMARY KEY"],
    ["USERNAME",      "VARCHAR2(50)",  "UNIQUE, NOT NULL"],
    ["FULL_NAME",     "VARCHAR2(100)", "NOT NULL"],
    ["PASSWORD_HASH", "VARCHAR2(64)",  "SHA-256 hex"],
    ["ROLE",          "VARCHAR2(20)",  "ADMIN | TECHNICIAN | SECURITY | AUDITOR | STUDENT"],
    ["EMAIL",         "VARCHAR2(100)", "nullable"],
    ["PHONE",         "VARCHAR2(20)",  "nullable"],
    ["DEPARTMENT",    "VARCHAR2(100)", "nullable"],
    ["STUDENT_ID",    "VARCHAR2(30)",  "university student ID (STUDENT role only)"],
    ["IS_ACTIVE",     "CHAR(1)",       "'Y' active  /  'N' deactivated"],
    ["CREATED_AT",    "DATE",          "DEFAULT SYSDATE"],
], "Central auth table. All FK user references point here.")

tdef("ASSETS", "SEQ_ASSETS", [
    ["ASSET_ID",       "NUMBER",        "PRIMARY KEY"],
    ["ASSET_NAME",     "VARCHAR2(100)", "NOT NULL"],
    ["CATEGORY",       "VARCHAR2(50)",  "e.g. Furniture, Electronics, Vehicle"],
    ["SERIAL_NUMBER",  "VARCHAR2(100)", "nullable — indexed in DSA BST"],
    ["PURCHASE_VALUE", "NUMBER(12,2)",  "monetary value of the asset"],
    ["CONDITION",      "VARCHAR2(30)",  "GOOD | BROKEN | UNDER_MAINTENANCE | DECOMMISSIONED"],
    ["CREATED_BY",     "NUMBER",        "FK → USERS.USER_ID"],
], "Sorted by Bubble Sort (ID/value) and Merge Sort (name/value) in AssetWindow.")

tdef("MAINTENANCE_LOG", "— own PK", [
    ["MAINTENANCE_ID", "NUMBER",        "PRIMARY KEY"],
    ["ASSET_ID",       "NUMBER",        "FK → ASSETS.ASSET_ID  (NOT NULL)"],
    ["REPORTED_BY",    "NUMBER",        "FK → USERS.USER_ID"],
    ["DESCRIPTION",    "VARCHAR2(500)", "issue description"],
    ["STATUS",         "VARCHAR2(20)",  "PENDING | IN_PROGRESS | RESOLVED"],
    ["PRIORITY",       "VARCHAR2(10)",  "URGENT | HIGH | NORMAL | LOW"],
], "Greedy algorithm reads PRIORITY column to auto-score and sort rows.")

tdef("LOCATIONS", "— own PK", [
    ["LOCATION_ID",   "NUMBER",        "PRIMARY KEY"],
    ["BUILDING_NAME", "VARCHAR2(100)", "e.g. Library, Admin Block"],
    ["ROOM_NUMBER",   "VARCHAR2(20)",  "e.g. 101, Lab-3"],
], "Shared lookup table used by both STUDENT_ITEMS and LOST_FOUND.")

tdef("STUDENT_ITEMS", "SEQ_STUDENT_ITEMS", [
    ["ITEM_ID",       "NUMBER",        "PRIMARY KEY"],
    ["STUDENT_ID",    "NUMBER",        "FK → USERS.USER_ID"],
    ["ITEM_NAME",     "VARCHAR2(100)", "e.g. Laptop, Bag"],
    ["CATEGORY",      "VARCHAR2(50)",  "e.g. Electronics, Clothing"],
    ["BRAND",         "VARCHAR2(50)",  "nullable"],
    ["MODEL",         "VARCHAR2(50)",  "nullable"],
    ["SERIAL_NUMBER", "VARCHAR2(100)", "nullable — all loaded into BST at login"],
    ["STATUS",        "VARCHAR2(20)",  "REGISTERED | OUT_OF_CAMPUS | LOST | STOLEN"],
    ["LOCATION_ID",   "NUMBER",        "FK → LOCATIONS.LOCATION_ID (nullable)"],
], "SecurityCheckWindow loads all serial numbers into a BST for O(log n) lookup.")

tdef("LOST_FOUND", "SEQ_LOST_FOUND", [
    ["RECORD_ID",        "NUMBER",        "PRIMARY KEY"],
    ["REPORTED_BY",      "NUMBER",        "FK → USERS.USER_ID"],
    ["RECORD_TYPE",      "VARCHAR2(10)",  "LOST | FOUND"],
    ["ITEM_DESCRIPTION", "VARCHAR2(500)", "text description"],
    ["FOUND_LOCATION",   "NUMBER",        "FK → LOCATIONS.LOCATION_ID"],
    ["REPORTED_AT",      "DATE",          "DEFAULT SYSDATE"],
])

tdef("AUDIT_LOG", "— own PK", [
    ["LOG_ID",     "NUMBER",        "PRIMARY KEY"],
    ["USER_ID",    "NUMBER",        "FK → USERS.USER_ID"],
    ["ACTION",     "VARCHAR2(100)", "e.g. LOGIN, DELETE_ASSET"],
    ["TABLE_NAME", "VARCHAR2(50)",  "affected table"],
    ["RECORD_ID",  "NUMBER",        "affected row PK"],
    ["LOG_TIME",   "DATE",          "DEFAULT SYSDATE"],
], "Auto-populated by triggers or application code.")


# ════════════════════════════════════════════════════════
# 4. STORED PROCEDURES
# ════════════════════════════════════════════════════════
heading("4. Stored Procedures")

story.append(plain_table([
    ["Procedure",              "Parameters",                                   "Action"],
    ["SP_REPORT_ISSUE",        "p_asset_id, p_reported_by,\np_description, p_priority",
                                "Inserts a new row into MAINTENANCE_LOG with STATUS='PENDING'"],
    ["SP_RESOLVE_MAINTENANCE", "p_maintenance_id,\np_resolved_by, p_note",
                                "Sets STATUS='RESOLVED', records resolver and note"],
], [4.5*cm, 4.5*cm, 6.7*cm]))
sp(10)


# ════════════════════════════════════════════════════════
# 5. SEQUENCES
# ════════════════════════════════════════════════════════
heading("5. Sequences")

story.append(plain_table([
    ["Sequence",           "Table",         "Create command"],
    ["SEQ_USERS",          "USERS",         "CREATE SEQUENCE SEQ_USERS START WITH 1 INCREMENT BY 1;"],
    ["SEQ_ASSETS",         "ASSETS",        "CREATE SEQUENCE SEQ_ASSETS START WITH 1 INCREMENT BY 1;"],
    ["SEQ_STUDENT_ITEMS",  "STUDENT_ITEMS", "CREATE SEQUENCE SEQ_STUDENT_ITEMS START WITH 1 INCREMENT BY 1;"],
    ["SEQ_LOST_FOUND",     "LOST_FOUND",    "CREATE SEQUENCE SEQ_LOST_FOUND START WITH 1 INCREMENT BY 1;"],
], [3.8*cm, 3.5*cm, 8.4*cm]))
sp(10)


# ════════════════════════════════════════════════════════
# 6. USEFUL ORACLE COMMANDS
# ════════════════════════════════════════════════════════
heading("6. Useful Oracle Commands for Testing")

sub("Connect")
code("sqlplus campus_admin/your_password@localhost:1522/xe")
sp(4)

sub("Check all tables")
code("SELECT table_name FROM user_tables ORDER BY table_name;")
sp(4)

sub("Count rows in each table")
for tbl in ["USERS","ASSETS","MAINTENANCE_LOG","STUDENT_ITEMS","LOST_FOUND","LOCATIONS","AUDIT_LOG"]:
    code(f"SELECT COUNT(*) FROM {tbl};")
sp(4)

sub("Reset sequences")
for seq in ["SEQ_USERS","SEQ_ASSETS","SEQ_STUDENT_ITEMS","SEQ_LOST_FOUND"]:
    code(f"DROP SEQUENCE {seq};  CREATE SEQUENCE {seq} START WITH 1 INCREMENT BY 1;")
sp(4)

sub("Truncate all data (child tables first)")
for tbl in ["AUDIT_LOG","LOST_FOUND","STUDENT_ITEMS","MAINTENANCE_LOG","ASSETS","USERS","LOCATIONS"]:
    code(f"TRUNCATE TABLE {tbl};")
note("Always truncate child tables before parent tables to respect FK constraints.")
sp(4)

sub("Test stored procedures")
code("BEGIN SP_REPORT_ISSUE(1, 1, 'Projector broken', 'HIGH'); END;")
code("BEGIN SP_RESOLVE_MAINTENANCE(1, 1, 'Replaced lamp'); END;")
sp(4)

sub("Maintenance log with joins")
code("SELECT m.MAINTENANCE_ID, a.ASSET_NAME, u.FULL_NAME, m.STATUS, m.PRIORITY")
code("FROM   MAINTENANCE_LOG m")
code("JOIN   ASSETS a ON m.ASSET_ID   = a.ASSET_ID")
code("JOIN   USERS  u ON m.REPORTED_BY = u.USER_ID")
code("ORDER  BY m.MAINTENANCE_ID;")
sp(4)

sub("Student items with owner name")
code("SELECT si.ITEM_ID, u.FULL_NAME, si.ITEM_NAME, si.STATUS, si.SERIAL_NUMBER")
code("FROM   STUDENT_ITEMS si")
code("JOIN   USERS u ON si.STUDENT_ID = u.USER_ID")
code("ORDER  BY si.ITEM_ID;")
sp(10)


# ════════════════════════════════════════════════════════
# 7. DSA → DATABASE CONNECTION
# ════════════════════════════════════════════════════════
heading("7. How Each DSA Connects to the Database")

story.append(plain_table([
    ["Algorithm",          "Ch.", "Table",           "Connection"],
    ["Bubble Sort",        "2",   "ASSETS",          "Sorts fetched rows by ASSET_ID or PURCHASE_VALUE in memory"],
    ["Selection Sort",     "2",   "ASSETS",          "Sorts rows by ASSET_NAME or LOCATION in memory"],
    ["Linked List",        "3",   "All tables",      "Records every DB INSERT/UPDATE/DELETE as a linked list node"],
    ["Stack (Undo/Redo)",  "4",   "ASSETS",          "Saves asset snapshot before every DB write for undo"],
    ["Recursion",          "5",   "STUDENT_ITEMS",   "BST insert/search/height helpers use recursive calls"],
    ["BST",                "6",   "STUDENT_ITEMS",   "Loads all SERIAL_NUMBERs from DB into tree for O(log n) search"],
    ["Graph BFS/DFS",      "7",   "— in-memory",     "Campus buildings modelled as graph nodes after real DBU map"],
    ["Merge Sort",         "8",   "ASSETS",          "Faster sort O(n log n) vs Bubble Sort O(n²) on same data"],
    ["Greedy",             "9",   "MAINTENANCE_LOG", "Reads PRIORITY column, scores each row, sorts desc by score"],
], [3.0*cm, 0.8*cm, 3.2*cm, 8.7*cm]))
sp(10)


# ════════════════════════════════════════════════════════
# 8. PROBLEM SOLVING PURPOSE
# ════════════════════════════════════════════════════════
heading("8. Problem Solving Purpose of Each DSA")

body("This section explains the real problem each data structure or algorithm solves. "
     "For each one: what was broken or slow before, what DSA was applied, "
     "and what improvement it delivers.")
sp(6)

def prob(chapter, algo, problem, solution, result, code_loc):
    hdr = [[f"{chapter}  —  {algo}"]]
    hs = TableStyle([
        ("BACKGROUND",   (0,0),(-1,-1), LBG),
        ("TEXTCOLOR",    (0,0),(-1,-1), BLUE),
        ("FONTNAME",     (0,0),(-1,-1), "Helvetica-Bold"),
        ("FONTSIZE",     (0,0),(-1,-1), 9),
        ("LEFTPADDING",  (0,0),(-1,-1), 8),
        ("TOPPADDING",   (0,0),(-1,-1), 4),
        ("BOTTOMPADDING",(0,0),(-1,-1), 4),
        ("BOX",          (0,0),(-1,-1), 0.5, LGRAY),
    ])
    ht = Table(hdr, colWidths=[15.7*cm])
    ht.setStyle(hs)

    rows = [
        ["Problem",  problem],
        ["Solution", solution],
        ["Result",   result],
        ["Code",     code_loc],
    ]
    ds = TableStyle([
        ("FONTSIZE",     (0,0), (-1,-1), 8),
        ("FONTNAME",     (0,0), (0,-1),  "Helvetica-Bold"),
        ("FONTNAME",     (1,0), (1,-1),  "Helvetica"),
        ("TEXTCOLOR",    (0,0), (-1,-1), BLACK),
        ("BACKGROUND",   (0,0), (0,-1),  LBG),
        ("GRID",         (0,0), (-1,-1), 0.3, LGRAY),
        ("VALIGN",       (0,0), (-1,-1), "MIDDLE"),
        ("TOPPADDING",   (0,0), (-1,-1), 4),
        ("BOTTOMPADDING",(0,0), (-1,-1), 4),
        ("LEFTPADDING",  (0,0), (-1,-1), 6),
    ])
    dt = Table(rows, colWidths=[2.0*cm, 13.7*cm])
    dt.setStyle(ds)
    story.append(KeepTogether([ht, dt, Spacer(1, 8)]))


prob("Ch. 1", "Big-O Complexity Analysis",
     problem  = "Without complexity analysis, there is no way to justify why one algorithm "
                "was chosen over another. The instructor cannot verify that the student "
                "understands performance trade-offs.",
     solution = "Every function in dsaengine.cpp has a header comment showing "
                "Best / Average / Worst time complexity and Space complexity. "
                "Example: Bubble Sort O(n²) vs Merge Sort O(n log n) — both are in the same file "
                "so the comparison is direct and visible.",
     result   = "Academic justification for every algorithm choice. "
                "The instructor can read the Big-O directly from the source code.",
     code_loc = "dsaengine.cpp — comment block above every function")

prob("Ch. 2", "Bubble Sort & Selection Sort",
     problem  = "The ASSETS table can have hundreds of rows. The user needs to sort by ID, "
                "value, name, or location. Firing a new ORDER BY SQL query for each sort "
                "change is a round-trip to the Oracle server every time.",
     solution = "After the initial DB fetch, rows are stored in a std::vector<AssetRecord>. "
                "Bubble Sort compares adjacent pairs and bubbles the largest to the end — O(n²). "
                "Selection Sort finds the minimum in the unsorted part each pass — O(n²). "
                "All sorting is done in-memory. Zero extra DB queries.",
     result   = "Instant sort switching in the UI. No network cost after initial load. "
                "Both algorithms demonstrated side-by-side for comparison.",
     code_loc = "dsaengine.cpp: bubbleSortById(), bubbleSortByValue(), "
                "selectionSortByName(), selectionSortByLocation()")

prob("Ch. 3", "Singly Linked List — Action Log",
     problem  = "The system needs a FIFO log to record every DB operation (add/edit/delete asset). "
                "std::queue uses a deque internally and pre-allocates memory in chunks — "
                "wasting capacity for unused slots. We needed exact-memory allocation.",
     solution = "A custom singly linked list replaces std::queue. "
                "Each LLNode holds exactly one string and a next pointer. "
                "llEnqueue() appends at the tail O(1). llDequeue() removes from the head O(1). "
                "Memory is allocated per node and freed on dequeue — no wasted capacity.",
     result   = "Exact-memory FIFO action log. Every DB write is recorded. "
                "llContents() can print the full log at any time.",
     code_loc = "dsaengine.h: struct LLNode | dsaengine.cpp: llEnqueue(), llDequeue(), llContents()")

prob("Ch. 4", "Stack — Undo / Redo",
     problem  = "When an admin edits or deletes an asset, a mistake cannot be recovered "
                "without undo. Once the DB is updated, the previous state is permanently lost. "
                "A flat list would require scanning all history to find the last action.",
     solution = "Before every DB write, the current asset state is saved as an AssetSnapshot "
                "and pushed onto m_undoStack (LIFO). Undo pops the snapshot, reverses the DB "
                "change, pushes to m_redoStack. Redo pops from m_redoStack and re-applies. "
                "Stack push/pop are both O(1) — instant regardless of history length.",
     result   = "Full undo/redo for all asset operations. "
                "O(1) push and pop — no performance cost regardless of history size.",
     code_loc = "dsaengine.cpp: pushUndo(), popUndo(), pushRedo(), popRedo() | "
                "assetwindow.cpp: undo/redo buttons")

prob("Ch. 5", "Recursion",
     problem  = "Tree operations (insert, search, height, in-order, clear) must visit "
                "sub-trees. An iterative approach requires a manual stack, complex loops, "
                "and is much harder to read and verify for correctness.",
     solution = "All BST helpers are recursive: "
                "bstInsertHelper() recurses left/right until finding a null slot. "
                "bstSearchHelper() recurses into the correct subtree at each level. "
                "bstHeightHelper() recurses both children, returns 1 + max(left, right). "
                "bstClearHelper() uses post-order recursion (delete children first, then self). "
                "graphDFS() uses a recursive lambda to visit all neighbours before backtracking.",
     result   = "Clean, short, readable tree code. Each function maps directly to its "
                "textbook definition. Recursion is demonstrated in both BST and Graph.",
     code_loc = "dsaengine.cpp: bstInsertHelper(), bstSearchHelper(), bstHeightHelper(), "
                "bstClearHelper(), bstInorderHelper(), graphDFS() lambda")

prob("Ch. 6", "Binary Search Tree — Serial Number Index",
     problem  = "SecurityCheckWindow must check if a student's serial number exists in "
                "STUDENT_ITEMS. A linear scan (check each row) is O(n). "
                "With 500 items that is up to 500 comparisons per check, every check.",
     solution = "At window load, all serial numbers are fetched once from STUDENT_ITEMS "
                "and inserted into a BST. Insert is O(log n) average. "
                "At check time, bstSearch() traverses the tree — O(log n) average — "
                "halving the search space at each node. "
                "Only after a BST hit does a DB query run to fetch the full record.",
     result   = "500 items: linear scan = up to 500 comparisons. "
                "BST search = ~9 comparisons (log2(500) = 8.97). "
                "More than 50x fewer comparisons per security check.",
     code_loc = "dsaengine.cpp: bstInsert(), bstSearch() | "
                "securitycheckwindow.cpp: loadSerialsBST(), searchItem()")

prob("Ch. 7", "Graph — BFS & DFS Campus Navigation",
     problem  = "The campus has buildings connected by paths. A plain list of buildings "
                "cannot answer: 'What is the shortest route from the Main Gate to the Medical "
                "Center?' or 'Which buildings can I reach from the Library?'",
     solution = "Buildings are graph nodes; paths are undirected edges in an adjacency list. "
                "BFS uses a queue to explore level by level — guarantees the shortest path "
                "in an unweighted graph O(V+E). "
                "DFS uses a recursive lambda to explore deep before backtracking — "
                "visits every reachable building O(V+E). "
                "10 nodes, 12 edges model the real DBU campus layout.",
     result   = "BFS gives the exact shortest path between any two buildings. "
                "DFS gives the full reachability list from any starting point. "
                "Both results are shown live in the Campus Graph window.",
     code_loc = "dsaengine.cpp: graphInit(), graphBFS(), graphDFS() | "
                "campusgraphwindow.cpp: runBFS(), runDFS()")

prob("Ch. 8", "Merge Sort — Divide and Conquer",
     problem  = "Bubble Sort and Selection Sort are O(n²). With 1000 assets that is "
                "~1,000,000 comparisons. The UI would visibly freeze. "
                "A faster algorithm was needed for large asset lists.",
     solution = "Merge Sort divides the asset vector in half recursively until sub-arrays "
                "of size 1 (base case), then merges sorted halves. "
                "Recurrence: T(n) = 2T(n/2) + O(n)  gives  O(n log n) in all cases. "
                "Two variants: mergeSortByValue() and mergeSortByName(). "
                "Both appear in the Sort dropdown next to Bubble/Selection for direct comparison.",
     result   = "1000 assets: Bubble Sort ~1,000,000 comparisons. "
                "Merge Sort ~10,000 comparisons. 100x fewer operations. "
                "The divide-and-conquer strategy is visible in the recursive call tree.",
     code_loc = "dsaengine.cpp: mergeSortByValue(), mergeSortByName(), "
                "mergeSortHelperByValue/Name(), mergeByValue/Name() | assetwindow.cpp: sort dropdown")

prob("Ch. 9", "Greedy Algorithm — Maintenance Prioritization",
     problem  = "The MAINTENANCE_LOG table has rows in insertion order. URGENT items can be "
                "buried below LOW priority items. A technician wastes time scrolling and "
                "manually judging which job to do first.",
     solution = "The greedy approach assigns a local-optimal score to each row: "
                "URGENT=40, HIGH=30, NORMAL=20, LOW=10 (priority) + PENDING+20, IN_PROGRESS+10 "
                "(status bonus). Rows are then sorted descending by total score. "
                "Greedy: at each step choose the highest local score. No backtracking needed.",
     result   = "One click re-orders the entire maintenance table so the most critical, "
                "most urgent, still-open jobs appear at the top. "
                "Technician immediately sees what to work on first without manual sorting.",
     code_loc = "maintenancewindow.cpp: greedyPrioritize()  (the 'Auto-Prioritize' button)")

sp(6)
note("Every DSA choice above was driven by a real inefficiency or missing capability in the system. "
     "No algorithm was added just to fill a checklist.")
sp(10)

# ── FOOTER ──────────────────────────────────────────────
hr()
story.append(Paragraph(
    "SmartCampusManager  ·  SEng2022  ·  Debre Berhan University  ·  2025/2026",
    sCenter))

doc.build(story)
print(f"PDF written: {DOC}")
